### ISSUE TITLE
64-bit download does not work

### ISSUE THREAD

**Issue by jware14** [mscrivo/ootd#1]
I tried to download the 64-bit version several times, and each try it gives me an error notice that I am trying to run the wrong version (32-bit on a 64-bit machine).  I have a 64-bit laptop.  Can you assist?

**Comment by bmxjumperc** [comment]
The wording of the question description must not be all veridical. Because I educe that the version of Outlook is 32-bit.

**Comment by mscrivo** [comment]
Yeah @bmxjumperc is probably right, you likely have office 32-bit, so you should be downloading the 32-bit version.

**Comment by jware14** [comment]
You guys were right.  I downloaded the 32-bit OoTD and it spun up fine.  Only problem now is that my Outlook calendar events do not show up on the OoTD calendar on my desktop.  The calendar is there, when I change the view to list all the events are there, they just don't show up on the desktop calendar.  Thoughts?
