### ISSUE TITLE
How do i pin ooth to the desktop so that "show desktop" doesn't hide it?

### ISSUE THREAD

**Issue by bilfrost** [mscrivo/ootd#10]
I typically use many windows, and to access ootd I have to minimize them. The fastest way to do that is to hit the "show desktop" button but that also hides ootd. Would suggest a pin button to make they stay on even when I show desktop.

**Comment by mscrivo** [comment]
Unfortunately Microsoft made it so that nothing can override that show Desktop button (also Win+D), but if you simply hover over the show desktop button instead of clicking it, all your other windows should disappear but OotD will still be visible.  Hopefully that works for you.
