### ISSUE TITLE
Can't run it

### ISSUE THREAD

**Issue by Xmuchao** [mscrivo/OotD#107]
**Describe the bug**
I first install the software. When I tried to run it, it failed to run, showing "there was an unknown error trying to run OotD".

My office version is Standard 2013.

**To Reproduce**
I first install the software. When I tried to run it, it failed to run, showing "there was an unknown error trying to run OotD".

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/43257886/45526025-123c7000-b808-11e8-94b5-1797a8fc6f9c.png)

**Windows Version**

- (eg. Windows 10 x64 1803)

**Additional context and log file**
Add any other context about the problem here
Also upload the most recent log file located in `C:\Program Files (x86)\Outlook on the Desktop\logs`

[2018-09-14.log](https://github.com/mscrivo/OotD/files/2381653/2018-09-14.log)

**Comment by Xmuchao** [comment]
I have downloaded the Version 3.5.3 Aug 20, 2017 (for Office 64-bit).

It works well.

**Comment by mscrivo** [comment]
Please try the latest version and re-open this if not fixed for you.
