### ISSUE TITLE
OotD Error

### ISSUE THREAD

**Issue by MoSLatF** [mscrivo/OotD#109]
**Describe the bug**
I tried to run OotD but I received this message:
![image](https://user-images.githubusercontent.com/43323812/45600901-8e9ba280-ba04-11e8-9e2a-232cdb33cf45.png)

![image](https://user-images.githubusercontent.com/43323812/45600893-83e10d80-ba04-11e8-8d8d-cc008a9ded85.png)

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/43323812/45600909-b559d900-ba04-11e8-8ca3-c32998377489.png)

**Windows Version**
- (eg. Windows 10 x64 1803)
Windows 7 x64 Home Premium

**Additional context and log file**
Add any other context about the problem here
Also upload the most recent log file located in `C:\Program Files (x86)\Outlook on the Desktop\logs`
[2018-09-16.log](https://github.com/mscrivo/OotD/files/2387023/2018-09-16.log)

**Comment by mscrivo** [comment]
Please try the latest version and re-open if it still doesn't work.
