### ISSUE TITLE
Multiple (overlaid) calendar view?

### ISSUE THREAD

**Issue by armandyte** [mscrivo/ootd#11]
Is is possible somehow OOTD to display several overlaid calendars in one instance??
(In the Outlook I see one big combined calendar which consists of several separate calendars. However on the desktop gadget I find only one default calendar excluding broader picture).

**Comment by mscrivo** [comment]
Yeah that's one limitation of the Outlook View Control supplied by Microsoft, it doesn't seem to handle that scenario, at least not from what I've been able to gather.  Sorry.

**Comment by udobehm** [comment]
Hi, Cal4Desktop offers the function to show several calendars overlaid on the desktop (see https://www.somebytes.de/produkte/cal4desktop/). Why is it not possible to program that with your program?? I absolutely need this function :((
