### ISSUE TITLE
Outlook on the Desktop Error

### ISSUE THREAD

**Issue by Jess0815** [mscrivo/OotD#112]
After installation, the following error message occurs:
There was an unknown error trying to run OotD. Please submit a bug at https://github.com/mscrivo/OotD/issues

Windows Version: Windows 10 x64

[2018-10-17.log](https://github.com/mscrivo/OotD/files/2486753/2018-10-17.log)

**Comment by mscrivo** [comment]
Please try the latest version and re-open this if not fixed for you.

**Comment by viccio22** [comment]
Hi,
after installing the latest version it also gives me the same error.

WIN10 X64

[2019-05-06.log](https://github.com/mscrivo/OotD/files/3148518/2019-05-06.log)
