### ISSUE TITLE
Could not open Calendar Error

### ISSUE THREAD

**Issue by Gentecintl** [mscrivo/OotD#113]
**Describe the bug**
When opening Ootd I receive a "Could not open Calendar error". Clicking Ok opens the program. I tried all the steps suggested in the FAQ non of them worked. I have two computers running the program with the same issue. Both Windows 10 machines.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Windows Version**
- (eg. Windows 10 x64 1803)
Windows 10 Pro 1803 build 17134.345

**Additional context and log file**
Add any other context about the problem here
Also upload the most recent log file located in `C:\Program Files (x86)\Outlook on the Desktop\logs

**Comment by mscrivo** [comment]
Please try the latest version and re-open this if not fixed for you.

**Comment by Gentecintl** [comment]
Same error after update to latest version.
