### ISSUE TITLE
OOD Stopped working 

### ISSUE THREAD

**Issue by wdg1258** [mscrivo/OotD#114]
Hello - LOVE your program and use it every day.  Unfortunately it just stopped working this morning and I get the following message - can you help?

![capture](https://user-images.githubusercontent.com/1655418/47644975-0ac9ef80-db46-11e8-8d04-769055821e01.PNG)

**Comment by mscrivo** [comment]
Try to repair your Office installation

**Comment by wdg1258** [comment]
Boom!  That worked!  Thanks!

 

Best regards,

William "Dee" Giarratano

678-956-4268

 <https://www.facebook.com/trailwoodbuilders/>
