### ISSUE TITLE
ootd and Office 365

### ISSUE THREAD

**Issue by PichlAlex** [mscrivo/ootd#12]
Hi!

i uninstalled Office 2007 and installed Office 365 to have a newer Software :-)

But now when i start ootd 3.2.5 (32bit) i get the following error message:

```---------------------------
Missing Requirements
---------------------------
This program requires Microsoft Outlook 2003 or higher.

Please install Microsoft Office and try again.
---------------------------
OK   
---------------------------
```
actually it looks exactly like Office 2013 ... Everything is installed on my desktop.

is it possible to use ootd with Office 365? i hope so!

best regards
Alex

**Comment by mscrivo** [comment]
hmm interesting.  I have not tested with Office 365, but from what I understood it's just the regular office apps with a subscription model, so Outlook should be installed and it should work fine.    Can you please attach the latest log file from "C:\Program Files (x86)\Outlook on the Desktop\logs" ?

**Comment by PichlAlex** [comment]
Hi!

thats the same that i thought - it seems that Office 365 is working a little bit different!

Content of the newest Log-File:
```
2015-09-09 21:30:00.6866 DEBUG Checking to see if there is an instance running. 
2015-09-09 21:30:00.7022 DEBUG Successfully read reg key: HKLM\Software\Microsoft\Office 
2015-09-09 21:30:00.7022 DEBUG Analyzing subkey '12.0' 
2015-09-09 21:30:00.7022 DEBUG Office Version: 12 
2015-09-09 21:30:00.7022 DEBUG Office 2003 or higher is installed, now checking for Outlook exe 
2015-09-09 21:30:00.7022 DEBUG Office path reported as:  
2015-09-09 21:30:00.7022 DEBUG Checking for Outlook exe in:  
2015-09-09 21:30:00.7022 ERROR Outlook path was reported as: Outlook.exe, but this file could not be found. 
2015-09-09 21:30:00.7022 DEBUG Outlook is not avaliable or installed. 
```

with that i tried to find my outlook.exe and i found it in "C:\Program Files\Microsoft Office 15\root\office15"
this path is not part of the %PATH% Environment variable.
in HKLM\Software\Microsoft\Office  i have to folders: "12.0" and "15.0" (and Outlook and Common)

hope that helps.

**Comment by mscrivo** [comment]
interesting, that helps a lot, thank you.  I'll see what I can do.

**Comment by mscrivo** [comment]
Does "Software\Microsoft\Windows\CurrentVersion\App Paths\OUTLOOK.EXE" exist in your HKLM?  I'm guessing not.  I'll have to setup a VM with Office 365 trial and see what it's doing.

**Comment by JFPAQUET** [comment]
Hello,
Same problem for me with Office 365.
To answer your question,
HKLM\Software\Microsoft\Windows\CurrentVersion\App Paths\OUTLOOK.EXE 
exists (Windows 7 64bit)
I have 2 REG_Z entries
- (Default) C:\Program Files\Microsoft Office 15\Root\Office15\OUTLOOK.EXE
- Path C:\Program Files\Microsoft Office 15\Root\Office15\
I hope you can solve this little issue, I am really looking forward to using 
Outlook on the Desktop

**Comment by mscrivo** [comment]
So I installed the trial of Office 365 in a clean Windows 8 install and OotD worked fine with it.  @JFPAQUET I have the exact same entries that you listed.  Can you attach your OotD log file?

**Comment by JFPAQUET** [comment]
Here are 2 log files, thanks for your help

JF

**Comment by mscrivo** [comment]
@JFPAQUET Can you attach them within the github issue in the browser?  Attachments don't appear to work via email.

**Comment by JFPAQUET** [comment]
Here are my OotD log files, unable to attach them as .log files,
so I send them in .png
![screenshot - 17-sep-15 13_21_42](https://cloud.githubusercontent.com/assets/14258191/9931818/30fe1470-5d3f-11e5-8891-02948ef6903e.jpg)
![screenshot - 17-sep-15 13_22_07](https://cloud.githubusercontent.com/assets/14258191/9931819/32c00188-5d3f-11e5-9899-aab81c09b6f1.jpg)

**Comment by mscrivo** [comment]
Thanks, I'll have another look to see if I can figure it out. I might ask
for some further info.

**Comment by JFPAQUET** [comment]
Thanks to you too , for your efforts.

J.F.

**Comment by mscrivo** [comment]
I think I may see the problem.  What regional settings are you using?  I assume it's something other than English US?

**Comment by mscrivo** [comment]
Can you guys try the pre-release build here: https://github.com/mscrivo/ootd/releases/tag/3.2.5.1 and let me know what happens?  Thanks

**Comment by JFPAQUET** [comment]
Hello, version 3.2.5.1 works !
After a little hesitation and the message "cannot read the calendar",
everything is fine and the calendar on desktop is operational.
BTW, my Windows settings are "English US"
Thanks

**Comment by mscrivo** [comment]
Glad to hear it

**Comment by PichlAlex** [comment]
Hi!

sorry for my disapperance - i was on vacation last week.

with Version 3.2.5.1 its not working for me and i now get the following log entries:
```
2015-09-21 19:57:54.4209 DEBUG Checking to see if there is an instance running. 
2015-09-21 19:57:54.4678 DEBUG Successfully read reg key: HKLM\Software\Microsoft\Office 
2015-09-21 19:57:54.4678 DEBUG Analyzing subkey '12.0' 
2015-09-21 19:57:54.4678 DEBUG Office Version: 12 Detected 
2015-09-21 19:57:54.4678 DEBUG Office Version: 12 Detected 
2015-09-21 19:57:54.4678 DEBUG Office 2003 or higher is installed, now checking for Outlook exe 
2015-09-21 19:57:54.4678 DEBUG Office path reported as:  
2015-09-21 19:57:54.4678 DEBUG Checking for Outlook exe in:  
2015-09-21 19:57:54.4678 DEBUG Outlook is not avaliable or installed. 
```

i use DEU (Österreich / Austria) as Locale

"Software\Microsoft\Windows\CurrentVersion\App Paths\OUTLOOK.EXE" does NOT exist in my HKLM

Thanks

**Comment by mscrivo** [comment]
@PichlAlex It looks like there is only information about Office 2007 in your registry.  What version of Office 365 do you have installed?  And it is 32-bit or 64-bit?   From what I'm seeing in the log file, there is no version of Office 365 installed or it's looking in the wrong place (ie 32-bit vs 64-bit locations)

**Comment by PichlAlex** [comment]
Hi!

i tried some things and finally its working now -  it seems there was a part of a broken Office 2007 installation somewhere - finally i reinstalled Office 365 that caused that now Office 2016 is on my computer instead of Office 2013. Both were installed in 32 bit.

however - its working fine :-)
thanks for your support!!!!!
