### ISSUE TITLE
blue time-line indication does not move: this leads to missing appointments

### ISSUE THREAD

**Issue by smoste** [mscrivo/OotD#120]
The OOTD Background image does never update the time-line.

Looking on the OOTD calender I have missed my appointments, because the line does not move and is no indication of the real time.

I am on Win7, Software\\Microsoft\\Office\\16.0\\Outlook, hope this helps to identify the outlook version

**Comment by Ivkosky** [comment]
I have the same issue on Windows 10, 64-bit. I would be grateful if this can be fixed.

**Comment by mscrivo** [comment]
Thanks for reporting, will hopefully take a look at this in the next few days.

**Comment by mscrivo** [comment]
I've been watching this over the past day, and I can't seem to reproduce.  My time bar keeps moving on it's own and is always at the correct time when I check.   Does it ever work for either of you?  ie. does it work for a while and then stop at some point?

**Comment by smoste** [comment]
no, it never works. But never mind, I got used to it

Stefan Schmors
Lehrer-Löhlein-Weg 6
91336 Heroldsbach
+49 9190 2151010
+49 9190 2529524 sipgate
+49 175 2762254 mobil

**Comment by mscrivo** [comment]
Could not reproduce
