### ISSUE TITLE
ERROR: This application requieres one of the following version of .NET Framework

### ISSUE THREAD

**Issue by afvega** [mscrivo/OotD#129]
he system give me the next message:
This application requieres one of the following version of .NET Framework: 
.NET Framework, Version 4.7.2
Do you want to install this .NETFramework version now?
I select Yes,  and the system tells me: **This Operating System does not support .Net Framework 4.7.2.** 

This is the windows version: Microsoft Windows [Version 10.0.10240].  64 bits In Spanish and Office 365 ProPlus both in Spanish

try disabling .NET from the windows features and install a previus version of .NET or a previus version of Ootd (32 bits too) and it didn't work.

I really try differents option and really like your program, please help me.
I would greatly appreciate your help

![ootd-02](https://user-images.githubusercontent.com/51809167/59482731-54422300-8e27-11e9-9367-18300ecea385.JPG)

![ootd-01](https://user-images.githubusercontent.com/51809167/59482698-2b219280-8e27-11e9-9ab2-e08f0d0042ee.JPG)

![UNISTALLE PREVIUS VERSION OF  NET](https://user-images.githubusercontent.com/51809167/59482649-f9103080-8e26-11e9-88b1-2d1e6dab5138.JPG)

**Comment by mscrivo** [comment]
Try this pre-release and let me know if it works: https://github.com/mscrivo/OotD/releases/download/3.99.83/ootd-3.99.86.0.exe
