### ISSUE TITLE
Pending Tasks

### ISSUE THREAD

**Issue by bsubhakar** [mscrivo/ootd#13]
In my outlook the pending tasks view is like the one attached in pic1 and in my OOTD, the tasks view is like the one in attached pic 2. I am unable to view my Pending tasks. Can you please help?
Thanks !!!
![pic1 - outlook view](https://cloud.githubusercontent.com/assets/14173327/9726638/6ce05440-5613-11e5-82da-138a6e9c5765.gif)
![pic2 - ootd view](https://cloud.githubusercontent.com/assets/14173327/9726639/6ce52448-5613-11e5-9c03-dd254b414dbf.gif)

**Comment by mscrivo** [comment]
If you right click on the OotD tray icon and then select "Outlook Views" and then "To-Do List" .. does that give you what you're looking for?

**Comment by bsubhakar** [comment]
it gives the same list as in attachment in 2 above.

**Comment by bsubhakar** [comment]
please find the attachment too. 
![todo_list_view](https://cloud.githubusercontent.com/assets/14173327/9755074/781ad6e4-56ec-11e5-9209-3ed53a13233e.gif)

**Comment by bsubhakar** [comment]
Any help on this? Thanks !!!

**Comment by mscrivo** [comment]
I'm not sure I understand what is going on here.  It seems that some tasks are displayed, but most are not?  What is the difference between those tasks?  I am unable to reproduce this on my end.

**Comment by bsubhakar** [comment]
My Outlook view as you see in the screenshot has my tasks for the day and overdue tasks. But if I try out that view in OOTD it doesn’t show the same view. It only show the way I have attached the second screenshot. Hope I am clear.

Thanks,

Subhakar Burri
Practice Director – Engineering Services
[Description: cid:image001.gif@01CB28D5.725A80B0]
E-mail:    sburri@osius.com<mailto:sburri@osius.com>
Office:   (+91) 40 30603011/12/13 Ext:301
              (+1) 213 408 3703 ext. 4726
Mobile:  (+91) 9849830603
               (+1) 818 932 2680

**Comment by mscrivo** [comment]
Hi @bsubhakar, sorry for the delay.  I am unable to reproduce this with Outlook 2016.  It's showing the tasks in OotD exactly as they appear in Outlook itself.  Perhaps this is an issue with the specific version of Office you are using.

**Comment by bsubhakar** [comment]
I am using Outlook 2103. Guess it’s a version issue then.

Thanks for all your help !!!!

Subhakar Burri
Practice Director – Engineering Services
[Description: cid:image001.gif@01CB28D5.725A80B0]
E-mail:    sburri@osius.com<mailto:sburri@osius.com>
Office:   (+91) 40 30603011/12/13 Ext:301
              (+1) 213 408 3703 ext. 4726
Mobile:  (+91) 9849830603
               (+1) 818 932 2680

**Comment by mscrivo** [comment]
Try the new release out and select "To-Do List"
