### ISSUE TITLE
Cannot start the app on windows 10

### ISSUE THREAD

**Issue by ele3fatty** [mscrivo/OotD#135]
**Describe the bug**
After updated to the last version, I cannot start outlook on the destop. I reinstalled. But still cannot open or start the software

**To Reproduce**

**Expected behavior**

**Screenshots**

**Windows Version**
- (eg. Windows 10 x64 1803)

**Additional context and log file**
Add any other context about the problem here
Also upload the most recent log file located in `C:\Program Files (x86)\Outlook on the Desktop\logs`

**Comment by mscrivo** [comment]
Can you please attach the logs?  Also check your event viewer for any errors related to the app and post them here please.

**Comment by ele3fatty** [comment]
> Can you please attach the logs? Also check your event viewer for any errors related to the app and post them here please.

Please guide me to find the logs and event viewers. I do not know where they are.

Thanks,
