### ISSUE TITLE
 Error HRESULT E_FAIL has been returned from a call to a COM component

### ISSUE THREAD

**Issue by tristanusa** [mscrivo/OotD#138]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Windows Version**
- (eg. Windows 10 x64 1803)

**Additional context and log file**
Add any other context about the problem here
Also upload the most recent log file located in `C:\Program Files (x86)\Outlook on the Desktop\logs`

**Comment by tristanusa** [comment]
Upon starting Windows 10 (Build 18362.19h1_release 190318-1202) x64 and autostart OotD, this message appears in an info box. Can I fix (no programmer experience) or does it need your fix? Thank you.

**Comment by mscrivo** [comment]
see for possible solution https://outlookonthedesktop.com/node/119
