### ISSUE TITLE
Comms Permission Error

### ISSUE THREAD

**Issue by erickws** [mscrivo/OotD#139]
I just installed the latest version of OOTD 4.0.152.0...   This error window pops up and I would love to know how to fix that if it is a permissions issue on my end.   I tried the 3.7.5 version as well... it runs but I receive a similar popup

![Call Rejected](https://user-images.githubusercontent.com/28110550/73610144-59b0d100-45a2-11ea-90c1-3a3209850534.PNG)

**Comment by mscrivo** [comment]
If you run OotD with admin privileges, does it work? Ie. try right clicking on the OotD icon and run as administrator.
