### ISSUE TITLE
Windows are not moving when not in calendar mode

### ISSUE THREAD

**Issue by Hizaack** [mscrivo/ootd#14]
Hello,
First of all, thank you for your great software. I think it will improve the efficiency of Outlook.

I don't know if it is a bug or I am doing it wrong, but here is my issue : 
When I change the type of the window (instance from calendar to other, like task or inbox), I can not move anymore the window. I can resize it, but not directly move it like when you have the cross with the calendar view.

Do you have the same? Can you help me?

![sans titre](https://cloud.githubusercontent.com/assets/14199145/9762767/e5920d1e-5705-11e5-8a76-08396c4515ce.jpg)
![sans titre2](https://cloud.githubusercontent.com/assets/14199145/9762768/e5956590-5705-11e5-8528-2f97c95b8ec5.jpg)

**Comment by mscrivo** [comment]
nice catch, I'll fix it asap.  thanks.
