### ISSUE TITLE
Error on Startup

### ISSUE THREAD

**Issue by tallraj69** [mscrivo/OotD#140]
On Windows 10 when Outlook on Desktop is launched, the attached error comes up. Office 365 is being used.
![Outlookondesktop error on launch](https://user-images.githubusercontent.com/51691425/76923739-4d869600-68fa-11ea-8f66-c7ff11df5c1c.png)

**Comment by mscrivo** [comment]
Please try the latest version and let me know if doesn't work. Thanks!
