### ISSUE TITLE
Could not read the Calendar

### ISSUE THREAD

**Issue by AlfaCharlie1973PG** [mscrivo/OotD#141]
**Describe the bug**
When I open the app, I get a spinning wheel. Then I click on anything and get the Could not read the calendar message box.

**To Reproduce**
When I open the app, I get a spinning wheel. Then I click on anything and get the Could not read the calendar message box.

**Expected behavior**
Nothing, Calendar automatically updates

**Screenshots**
![Could not read the calendar](https://user-images.githubusercontent.com/62720681/80161233-b8805800-859d-11ea-9872-4c800dc7f933.png)

**Windows Version**
Windows 10 x64 1903 18362.778

**Additional context and log file**
Add any other context about the problem here
Also upload the most recent log file located in `C:\Program Files (x86)\Outlook on the Desktop\logs
[2020-04-23.log](https://github.com/mscrivo/OotD/files/4525944/2020-04-23.log)
`

**Comment by mscrivo** [comment]
This is an Outlook bug, see here for possible workaround: https://social.technet.microsoft.com/Forums/ie/en-US/5bf4ad1b-e8fc-40a2-8cdd-5970cfb66b27/outlook-2010-could-not-read-the-calendar?forum=outlook

**Comment by AlfaCharlie1973PG** [comment]
Thanks for the feedback. I have followed all the workarounds from that discussion but I continue having the same issue. Unfortunately, I will not be able to use your app (and I really wanted)

Regards,
Alfredo

Email Classification: Business Use (unless specified differently above)
