### ISSUE TITLE
Does not recognize Outlook 2016

### ISSUE THREAD

**Issue by ruiprieto** [mscrivo/OotD#142]
**Describe the bug**
on v4.x.xxx.x after installation a pop-up window states:

"Missing Requirements: This program requires Microsoft Outlook 2010 or higher. Please install Microsoft Office and try again."
![error](https://user-images.githubusercontent.com/32093541/81727604-c0cf0300-9478-11ea-9220-631c3f7a6859.jpg)

Problem: MS Office 2016 is installed, thus it should recognize it.

System:
Windows 10 Pro 64
HP Envy with i7 @ 1.8 GHz; 16 G RAM; 
Office 2016 Pro

**Comment by SSBN608** [comment]
Same problem but with Office Pro 2019 and a partial install of off 2010 (picture manager module).
Went back to old 3.7.5 install to get around the problem with this latest update.

**Comment by ldefibaugh** [comment]
Same problem - Office Professional Plus 2016 installed, but the same "missing requirements" pop-up.  
Windows 10 Education edition.
Dell Latitude 550
8GB RAM, i5 @ 1.6Ghz

**Comment by mscrivo** [comment]
Can you please attach your logs here to help me get to the bottom of it?  They should be in C:\Program Files (x86)\Outlook on the Desktop\logs.

Thanks!

**Comment by ldefibaugh** [comment]
[2020-06-17.log](https://github.com/mscrivo/OotD/files/4794609/2020-06-17.log)

**Comment by SSBN608** [comment]
[2020-06-17.log](https://github.com/mscrivo/OotD/files/4794990/2020-06-17.log)
FYI now running Win10 Ver 1909 and Office 365 installed to;
C:\Program Files\Microsoft Office\root\Office16\
![Error](https://user-images.githubusercontent.com/65566220/84947786-4a38ad00-b097-11ea-8cf2-c733d729bfe6.jpg)

**Comment by mscrivo** [comment]
Thank you both, the logs helped identify the issue and I'll get a new version for you to try out shortly.

**Comment by mscrivo** [comment]
New version with fix is out. Thanks again!
