### ISSUE TITLE
toggle top bar and white border (maybe by locking)

### ISSUE THREAD

**Issue by tsteffek** [mscrivo/OotD#143]
**Is your feature request related to a problem? Please describe.**
Not a problem, it's purely aesthetic. Currently, there's a relatively big border around the calendar, which doesn't match the calendar's color and to be honest looks a little Windows XP-ish.

**Describe the solution you'd like**
Make it invisible/transparent. I can see it as an indicator, that the calendar can be moved - so maybe it could disappear, when locking the screen?

**Describe alternatives you've considered**
I guess matching the calendar color works as well, however, as I assume this program is basically like an iframe for Outlook, this might be hard to implement.

**Additional context**
![image](https://user-images.githubusercontent.com/28529410/81939518-bdfa1c80-95f6-11ea-9d43-808ac5dabdc6.png)
Would look a lot cleaner without this, wouldn't it?

**Comment by mscrivo** [comment]
I would agree .. in fact that was not there in the beginning, I added it after multiple feature requests for the features it provides and I tried to make it as unobtrusive as possible.  A setting to toggle it on/off would be nice, I'll see if I can find some time to do it.  

PR's are always welcome as well :)

**Comment by mscrivo** [comment]
I liked your idea of hiding when locking, so I implemented that. Thanks for the suggestion!
