### ISSUE TITLE
Outlook 2013 not recognized

### ISSUE THREAD

**Issue by Defskins** [mscrivo/OotD#144]
New download of Office 2013, including Outlook 2013. OotD not recognizing the program

Downloaded OotD but unable to load.

If my software is valid, OotD should load.

![image](https://user-images.githubusercontent.com/66048290/83093685-82833780-a065-11ea-8122-d6756c947492.png)

**Windows Version**
Windows 10 x64 1803

**Additional context and log file**
Add any other context about the problem here
Also upload the most recent log file located in `C:\Program Files (x86)\Outlook on the Desktop\logs`

**Comment by mscrivo** [comment]
Fixed version is available, thanks!
