### ISSUE TITLE
"In" the desktop

### ISSUE THREAD

**Issue by Cabcabcab** [mscrivo/OotD#145]
Hello,

I just discovered your software. It seems practical and I may use it.
One thing bothers me. It seems to me that the open window of OotD is "on" the Windows desktop and not "in" the desktop. Indeed, when I execute a " + D", it disappears.
Did I forget to select an option?
Thanks for your help.
Regards,

PaTrice

**Comment by mscrivo** [comment]
Unfortunately, with Windows 10, Microsoft has made it really difficult to keep any app pinned to the desktop. I've only seen one application (rainmeter) do it and it took a lot of work from what I can see in their codebase.  One thing that does work, is hovering over the bottom rightmost part of the your taskbar, that will hide everything except for OotD.  Hope that helps.
