### ISSUE TITLE
Saving Task / To-Do List View Settings Between Sessions

### ISSUE THREAD

**Issue by Geotech-Engineer** [mscrivo/OotD#146]
When OOTD starts, it does not save the view settings, and custom sorting, associated with the task / to-do list. Can the program be modified to save the settings between sessions?

Otherwise, great program! Thank you for all of your work.

**Comment by FabrizioDonnarumma** [comment]
I have the same request. 
I thought the setting would be in an xml file, similar to outlook, but I cannot find one.

**Comment by mscrivo** [comment]
Thanks for the great suggestion! I have implemented a fix that should save customizations to notes, todos and task views.

Will put out a release shortly
