### ISSUE TITLE
Plugi in for Unread Email

### ISSUE THREAD

**Issue by 11OF10S** [mscrivo/OotD#147]
**Is your feature request related to a problem? Please describe.**
I would like to  have a option to display all unread emails  not  just te inbox  or other folders.

**Describe the solution you'd like**
A option to seleckt Unread  emails in the drop down menu like Inbox, Task  ect. 

**Describe alternatives you've considered**
Inbox filter  for unread or search in Inbox.

**Comment by mscrivo** [comment]
Not really possible with this app, sorry.
