### ISSUE TITLE
The download of June 20 4.0.178 with the fix has no download file, downloads as 0kb.  Still getting error and cannot download the update.  I am on Windows 10X64 1803

### ISSUE THREAD

**Issue by MarvMary** [mscrivo/OotD#148]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Windows Version**
- (eg. Windows 10 x64 1803)

**Additional context and log file**
Add any other context about the problem here
Also upload the most recent log file located in `C:\Program Files (x86)\Outlook on the Desktop\logs`

**Comment by mscrivo** [comment]
Hi @MarvMary  .. try downloading it directly from here; https://github.com/mscrivo/OotD/releases/download/4.0.178/ootd-4.0.178.0.exe
