### ISSUE TITLE
"Could not read the calendar" error

### ISSUE THREAD

**Issue by knightsolutions** [mscrivo/OotD#149]
**Describe the bug**
After installing I get this error, see screen shot. 

**To Reproduce**
Opening Outlook on the Desktop

**Expected behavior**

**Screenshots**
See attached
![OOTD Error](https://user-images.githubusercontent.com/69179516/89245891-3946f980-d64d-11ea-9a46-3fcce4c7f46d.png)

**Windows Version**
Windows 10 x64

**Comment by knightsolutions** [comment]
Also comes up when I change views in OOTD

**Comment by jimbrig** [comment]
same here

**Comment by mscrivo** [comment]
This is an Outlook issue .. see here for a possible solution:

https://social.technet.microsoft.com/Forums/ie/en-US/5bf4ad1b-e8fc-40a2-8cdd-5970cfb66b27/outlook-2010-could-not-read-the-calendar?forum=outlook

**Comment by knightsolutions** [comment]
Removing second language worked 😊


Regards
Robert Hudman

+61 408 083 076

+61 2 9160 1254

robert@knightsolutions.com.au
[cid:image001.png@01D6746C.561E3AC0]

[cid:image002.png@01D6746C.561E3AC0]<https://calendly.com/knight-solutions>
