### ISSUE TITLE
Feature : Add a button "New message" in the title bar of the Inbox instance.

### ISSUE THREAD

**Issue by Hizaack** [mscrivo/ootd#15]
Appanrently, you can not write a new email directly from OotD.
It would be nice to do this enhancement : a button in the title bar of the emails window to quickly writes new email.
And add the shortcut Ctrl+N for new message when the focus is on the email instance.

What do you think about that?

Thank you for you software,

Regards

**Comment by mscrivo** [comment]
Yeah I had thought of doing that before, but I risk cluttering up the UI too much if I start adding buttons for everything.  I was already hesitant to add the current bar you see at the top of each instance.  Adding a single new button might not be too bad though, I'll see how it works out.  

Thanks for the suggestion.

**Comment by Hizaack** [comment]
I agree, the goal is not to clutter the window. And the others button can bo reach when right-click on an email. Only New Message have no way to access from OotD. 
Maybe a button with a envelope style, with the size of the buttons in Calendar view task bar ?
Or if you don't want/can't to add the button, maybe just adding at least the shortcut Ctrl+N when the focus is on the Inbox instance?

Thank you for your great work!

**Comment by Hizaack** [comment]
Maybe just add working shorcuts for New Message and Delete?

Best regards,

**Comment by mscrivo** [comment]
I did not implement a delete button, because it's much easier to right click on the item you want to delete and do it that way.
