### ISSUE TITLE
Next/Previous error when on Day View

### ISSUE THREAD

**Issue by knightsolutions** [mscrivo/OotD#150]
**Describe the bug**
When on Day view, using the green arrows for next/previous does not move to the next/previous day....it skips to seemingly random days. 

**To Reproduce**
1. Use Day View
2. Click Next/Previous

**Expected behavior**
It should move to the next or previous day in the calendar. 

**Screenshots**
See attached video. 

**Windows Version**
Windows 10

**Additional context and log file**
Add any other context about the problem here
Also upload the most recent log file located in `C:\Program Files (x86)\Outlook on the Desktop\logs
[2020-08-06.log](https://githu
![2020-08-06_12-44-25](https://user-images.githubusercontent.com/69179516/89484790-99bb6f80-d7e2-11ea-8da1-cb4bc0356dac.gif)

b.com/mscrivo/OotD/files/5032249/2020-08-06.log)

`

**Comment by mscrivo** [comment]
Thanks for the report @knightsolutions! .. can you give me a little more info on your setup?  Are you using multiple instances in OotD?  Does it not work right off the bat? or is there some sequence of events that causes it to go all random like that?  I'm trying to reproduce the error and haven't been able to so far.

**Comment by knightsolutions** [comment]
Hi Michael
Standard set up, single instance of OotD.
I have view set as day view, it opens to that by default and the error is always there.

Regards
Robert Hudman
+61 408 083 076
+61 2 9160 1254
robert@knightsolutions.com.au

KNIGHT SOLUTIONS


________________________________

**Comment by knightsolutions** [comment]
Hi Michael
Does this mean it has been fixed?

Regards
Robert Hudman
+61 408 083 076
+61 2 9160 1254
robert@knightsolutions.com.au

KNIGHT SOLUTIONS


________________________________

**Comment by mscrivo** [comment]
Potentially .. can you try this per-release version and let me know? https://github.com/mscrivo/OotD/releases/download/4.0.193/ootd-4.0.193.0.exe

**Comment by knightsolutions** [comment]
Can you provide me a 64 bit version?

[cid:image001.png@01D66E42.8926DA10]


Regards
Robert Hudman

+61 408 083 076

+61 2 9160 1254

robert@knightsolutions.com.au
[cid:image002.png@01D66E42.8926DA10]

[cid:image003.png@01D66E42.8926DA10]<https://calendly.com/knight-solutions>

**Comment by mscrivo** [comment]
Sorry about that, can you try this one: https://github.com/mscrivo/OotD/releases/download/4.0.194/ootd-4.0.194.0.exe

**Comment by knightsolutions** [comment]
Thanks Michael
Seems to be working now, so great!

Note: Still getting the “Cannot Read Calendar” error – which I have always had with OotD (see attached).

Cheers


Regards
Robert Hudman

+61 408 083 076

+61 2 9160 1254

robert@knightsolutions.com.au
[cid:image001.png@01D66F52.FB286BE0]

[cid:image002.png@01D66F52.FB286BE0]<https://calendly.com/knight-solutions>

**Comment by mscrivo** [comment]
That's good to hear!

Yeah the could not read calendar is a common error people run into. It's
out of my control unfortunately, I haven't been able to track down why or
when it happens. If I find a solution I'll let you know.

**Comment by knightsolutions** [comment]
Much appreciated.

Regards
Robert Hudman
+61 408 083 076
+61 2 9160 1254
robert@knightsolutions.com.au

KNIGHT SOLUTIONS


________________________________
