### ISSUE TITLE
Request to remove white borders of OOTD widget interface.

### ISSUE THREAD

**Issue by nowhereman1935** [mscrivo/OotD#152]
I think it is possible to remove the thick white borders of the OOTD widget interface or at least make the frame/line minimal or nearly borderless for your next update. It will look good if, not better, on desktop as it can go along with different backgrounds. 

Looking forward for this feature/option to adjust/granulate boarder thickness.

Kudos!

**Comment by mscrivo** [comment]
Sorry for the late reply. There are no white borders on the app, please provide a screenshot of what you're seeing.
