### ISSUE TITLE
Could not read calendar error

### ISSUE THREAD

**Issue by gittygatta** [mscrivo/OotD#159]
**Describe the bug**
When I launch ootd, I get an error "could not read the calendar". I followed the steps in FAQs and repaired the PST but I still get the error.

**To Reproduce**
Closed outlook, ran inbox repair, then relaunched outlook and opened ootd and I still get the error

**Expected behavior**
no errors

**Screenshots**
![image](https://user-images.githubusercontent.com/58463691/104980407-8c541380-5a17-11eb-98fe-3f365d2fb7b2.png)
![image](https://user-images.githubusercontent.com/58463691/104980424-95dd7b80-5a17-11eb-8128-eadadac09533.png)
![image](https://user-images.githubusercontent.com/58463691/104980463-a4c42e00-5a17-11eb-8baa-4e78dd8d1e19.png)

**Windows Version**
- (eg. Windows 10 x64 1803)
- Windows 10 x64 19042

**Additional context and log file**
Add any other context about the problem here
Also upload the most recent log file located in `C:\Program Files (x86)\Outlook on the Desktop\logs
[2021-01-19.log](https://github.com/mscrivo/OotD/files/5833270/2021-01-19.log)
`

**Comment by wsmelton** [comment]
Receiving this as well, but I'm not using any PST files. The calendar is viewing properly, it just pops that error message up when changing views on OOTD.

**Comment by drobins9** [comment]
Also receiving this, also not using any PST files.  Two exchange accounts in Outlook and that's it.

**Comment by mscrivo** [comment]
Microsoft may have finally fixed this issue: https://answers.microsoft.com/en-us/msoffice/forum/msoffice_outlook-mso_win10-mso_365hp/microsoft-outlook-error-could-not-read-the/f0107a27-849c-4584-a8a7-7588fdae9111

Anyhow, going to close this issue as there is literally nothing I can do to fix it or mitigate it.
