### ISSUE TITLE
Can't install newer verisons

### ISSUE THREAD

**Issue by cgr6513** [mscrivo/OotD#160]
I'm running version 3.7.5 because every version after that gives me an error code that I'm trying to install the wrong version of OotD - e.g. 32 bit OotD with 64 bit Outlook or vice versa...however there's now only one version of OotD which supposedly contains both 32 bit and 64 bit. My outlook is 64 bit. I'd love to upgrade to the latest version, but it will not let me!

**Comment by cgr6513** [comment]
I'm running version 3.7.5 because every version after that gives me an error code that I'm trying to install the wrong version of OotD - e.g. 32 bit OotD with 64 bit Outlook or vice versa...however there's now only one version of OotD which supposedly contains both 32 bit and 64 bit.  My outlook is 64 bit.  I'd love to upgrade to the latest version, but it will not let me!

**Comment by cgr6513** [comment]
This is the error I get when trying to install any version post 3.7.5

![wrong version](https://user-images.githubusercontent.com/51496766/105410375-d861ac80-5bff-11eb-8e6f-88e248e0327a.jpg)

**Comment by mscrivo** [comment]
Sorry for the late reply, if you're still facing this issue, could you upload the log file here?  It should be in C:\Program Files (x86)\Outlook on the Desktop\logs

**Comment by cgr6513** [comment]
Hi Michael – I just tried installing 4.0.22.1 and I continue to get the same error:

 



 

 

I have the 64-bit Office installed.  The last version that I could get to work (and still use) is 3.7.5.0.  I’ve attached the log file as you requested.

 

Thanks!

 

Gary

**Comment by mscrivo** [comment]
I do not see the log file, I think you might have to attach it directly to this issue via your web browser.

**Comment by cgr6513** [comment]
[2021-06-19.log](https://github.com/mscrivo/OotD/files/6681171/2021-06-19.log)

**Comment by cgr6513** [comment]
Ok…it’s attached to the issue on GitHub

**Comment by mscrivo** [comment]
Interesting, thanks!  If you've got a moment, can you take a screenshot of the version information from inside Outlook itself?

Looks something like this:
![image](https://user-images.githubusercontent.com/275524/122653417-4a3c1480-d112-11eb-8c29-5518206f1a9c.png)

**Comment by cgr6513** [comment]
![about office](https://user-images.githubusercontent.com/51496766/122653607-a6ebff00-d113-11eb-81d1-a478718d81a0.jpg)

**Comment by cgr6513** [comment]
See jpg here and on Github.

 

Gary

**Comment by mscrivo** [comment]
Great, thanks! I'll have to see if I can reproduce it with Office 2010. Have you considered upgrading? that's quite old :)

**Comment by cgr6513** [comment]
The functionality I use in outlook, excel and word is there in 2010 so I haven’t seen the need to spend more money so long as it continues to work. I appreciate your efforts.   OotD is a great program. I have my iCloud calendar always in front of me when working on the PC.  

Thanks again.  

I noticed in the log file that something is showing as  or registered.  If there’s a specific dll that I need to register,I can try doing that.

**Comment by mscrivo** [comment]
Yeah that means something's not right with your outlook installation, but unfortunately, no idea how to fix it. 

Office 2010 support ended in 2020, so I can't even find ISO's from Microsoft to install it anymore. Unfortunately, I don't think I will be able to help.

**Comment by cgr6513** [comment]
Ok. Thx. I suppose I could try to reinstall outlook.

**Comment by cgr6513** [comment]
Great news, Michael!  I ran the repair on Microsoft Office and then did the update to OotD and it now works!


Here’s the log file if you’re interested….but all seems well.  Thanks again for a great program!

Gary
[2021-06-19.log](https://github.com/mscrivo/OotD/files/6681457/2021-06-19.log)

**Comment by mscrivo** [comment]
Glad to hear it!

**Comment by cgr6513** [comment]
Well…I rebooted today and back came the wrong version 32/64 bit error message.  Had to delete ootd and reinstall version 3.75.   I guess I’ll have to continue to live with it until I update Outlook…just wanted to let you know.
