### ISSUE TITLE
Unable to open the application, .NET error

### ISSUE THREAD

**Issue by Ivkosky** [mscrivo/OotD#161]
The application cannot be started, it shows a popup requesting me to install .NET. However, when I select "yes", nothing happens:

![image](https://user-images.githubusercontent.com/20471895/105663900-c7a98300-5eec-11eb-993e-4dfc9268dd1f.png)

Also, I have all the possible .NET installations on my computer, hence I do not understand what more is required?

![image](https://user-images.githubusercontent.com/20471895/105663817-a34da680-5eec-11eb-8c4e-36e0c820aa07.png)

Thanks for your help.

**Comment by mscrivo** [comment]
I wonder if it detected the developer packages on your system and skipped the installation. Can you try installing the .net core 5.0.2 desktop x86 runtime from here: https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-5.0.2-windows-x86-installer

**Comment by Ivkosky** [comment]
Hi, thanks for your reply. I have uninstalled all the .NET packages that you see in my screenshot above, restarted computer, installed the x86 version of .NET 5.0.2 as suggested, installed Outlook on the Desktop, but the same issue persists. The same message and same no action after clicking on "yes" to install .NET. Any ideas?

**Comment by mscrivo** [comment]
If you've uninstalled all of them, you'll likely also need the x64 runtime as well: https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-5.0.2-windows-x64-installer

**Comment by Ivkosky** [comment]
Brilliant, it works now. Thanks a lot!
