### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by wdobbin** [mscrivo/OotD#163]
Error report each time I try and install

Install program

Application to open

![Bug](https://user-images.githubusercontent.com/78522636/106845047-eee32a00-670e-11eb-8c7d-05490ad95f5a.JPG)

[**Windows Version**
OS name: Microsoft Windows 10 Pro
Version:10.0.18363 build 18363 

[2021-02-04.log](https://github.com/mscrivo/OotD/files/5923208/2021-02-04.log)

**Comment by mscrivo** [comment]
That indicates there is a problem with your Office installation. Easiest thing to try is uninstalling and reinstalling Office as the causes could be numerous. There's some repair options you can try here as well: https://outlookonthedesktop.com/faq
