### ISSUE TITLE
Opacity

### ISSUE THREAD

**Issue by leliobrito** [mscrivo/OotD#167]
It feels like I'm being a total rookie here, but I can seem to find the 'opacity' controle in my menu. I've read FAQ and issues posted, but ti feels like 'opacity' should be somewhere in the menu easily accessible and I can't see it (version 4.0.221).
Thanks! The app is GREAT!

**Comment by mscrivo** [comment]
> It feels like I'm being a total rookie here, but I can seem to find the 'opacity' controle in my menu. I've read FAQ and issues posted, but ti feels like 'opacity' should be somewhere in the menu easily accessible and I can't see it (version 4.0.221).
> Thanks! The app is GREAT!

Hi! It's not in the menu .. it's a slider in the top left corner of the window

**Comment by leliobrito** [comment]
Much appreciated! found it! Truly sorry to take your time... i really enjoy the OotD experience! Thanks again.
