### ISSUE TITLE
Missing information in Inbox instance after actions

### ISSUE THREAD

**Issue by Hizaack** [mscrivo/OotD#17]
Hello,
I am facing an issue with the Inbox instance.
First, I can see all my emails and the object of them.
The Inbox instance can not retrieve or display emails information like Object, Received date, and following when : 
- Pressing windows key
- Lock/Unlock session
- Displaying the desktop (Win+D)
  ![sans titre](https://cloud.githubusercontent.com/assets/14199145/9910423/5bba8c54-5c9d-11e5-8859-b4dea57c4185.jpg)
  ![sans titre2](https://cloud.githubusercontent.com/assets/14199145/9910424/5bbe433a-5c9d-11e5-96ee-7039d3bef11b.jpg)

Best regards,

**Comment by mscrivo** [comment]
Hi there, these are likely limitations of what the outlook view control allows for.  There probably isn't much I can do about it.  The outlook view control is supplied by Microsoft with Office and they control what the view actually looks like.  OotD just presents that control in a useful way.

**Comment by mscrivo** [comment]
I'm not quite sure I understand the issue.  When you lock your computer, you are unable to interact with emails in OotD?

**Comment by Hizaack** [comment]
Hello,
Sorry for the delay. Yes I can interact with emails in OotD, but informations of emails like objects or reception date, and flags, are missing like you can see in the second picture.

Best regards,
