### ISSUE TITLE
showing different catalog at the same time 

### ISSUE THREAD

**Issue by suprerene** [mscrivo/ootd#19]
It was just a comment instead of a bug. It would be awesome if I am able to show calendar, tasks and email at the same time without the need of switching it each time. 
If the programme already able to do this and i've missed it, please tell me. Thank you, love this programme.

**Comment by mscrivo** [comment]
You can!  Right click on the tray icon at the bottom right, and click "Add Instance."  You can configure each instance to show a different Outlook view.
