### ISSUE TITLE
Calendar - looking to the futuer

### ISSUE THREAD

**Issue by lgullestrup** [mscrivo/OotD#21]
It appears that while in week view, trying to look too far ahead in the future, and the calendar will go back to earlier in the year.

Got example today is 21st October 2015, i click the right arrow button twice and it takes me to 6th of April 2015

**Comment by mscrivo** [comment]
strange, I'm not seeing that here.  A few questions:

1. Is this in the work week view, or full week view?
2. If you click it once, how many days ahead does it skip?  If you click it again, how many does it skip this time?
3. What region is your system set to?

**Comment by lgullestrup** [comment]
This glitch seems to occur in all views except month. It is also a network calendar. i dont know if that is important or not (IE, the calendar is available to any device logged in with my network account)

I created a video showing the glitch: 
https://youtu.be/7rcrEkwYiIY

(dont mind the blurriness, this was done post recording).

i would believe our region is set to Brisbane..

**Comment by mscrivo** [comment]
Thanks for the video, I'll take a look.

**Comment by jrussell11** [comment]
I can't repro this any longer. Can anyone?
