### ISSUE TITLE
Support non-office outlook

### ISSUE THREAD

**Issue by CoenraadS** [mscrivo/OotD#215]
**Is your feature request related to a problem? Please describe.**
Hello, I just installed this app, but it didn't work because I don't have an office installation. However these days Outlook has replaced the default mail app in windows, and lots of people like me use the non-office version of outlook.

Source: https://support.microsoft.com/en-us/office/getting-started-with-the-new-outlook-for-windows-656bb8d9-5a60-49b2-a98b-ba7822bc7627

**Describe the solution you'd like**
Would be great if it worked with the default outlook app

**Comment by mscrivo** [comment]
Sorry not possible with the architecture of this app, you'd have to find some other app to do that
