### ISSUE TITLE
Tasks: Not showing emails with a "Follow up" flag

### ISSUE THREAD

**Issue by kristianrl** [mscrivo/ootd#22]
I would like my Tasks lists to show my emails with a *Follow up*-flag.

In Outlook, I get a list like this with the Tasks->Simple View:
![outlook](https://cloud.githubusercontent.com/assets/2519890/10687476/a9cb3c62-796d-11e5-95df-81cce3231f72.png)

In Outlook On The Desktop, I only get the tasks created as *Tasks*, not the emails with a *Follow up*-flag.
![ootd](https://cloud.githubusercontent.com/assets/2519890/10687477/a9cb4bbc-796d-11e5-8707-e3b7e8d7c3fb.png)

How do I show the full list in Outlook On The Desktop?
I have a sense that this is related to which *Folder* OOTD is looking into. Supposing the default is the *Tasks* folder, is there a way to have it look into any folder on all accounts?

Thanks for an excellent tool!

**Comment by mscrivo** [comment]
Have you tried using the "Select Folder" functionality?  or "Outlook Views"?  Both are available by right clicking on the OotD tray icon.

**Comment by kristianrl** [comment]
Yes, I tried this, but with no luck.
Can you get it to work when selecting a different folder?

**Comment by mscrivo** [comment]
I think I know what the problem is.  In Outlook there is a distinction between the "Task" list and the "To Do" list.  OotD seems to be showing the Task list only, but you're looking for the To-Do list.  I'm going to see if the To-Do list is something that can be exposed as well.

**Comment by mscrivo** [comment]
Try the new release out.

**Comment by kristianrl** [comment]
Great, it works perfectly! Thanks a lot!
