### ISSUE TITLE
ootd is not showing my appointments

### ISSUE THREAD

**Issue by amerzang** [mscrivo/ootd#23]
Help please, I am new to ootd, doing a trial run. I am using Windows 7 Pro and Office 2016 (365) (both 64bit), when i first loaded OoTD, it showed my appointments and I REALLY liked the program, now, after reboot, it shows a blank calendar. It has that little circle in the middle, that rotates,  as if it is trying to load something, but nothing fills in. Any ideas or fixes?

**Comment by mscrivo** [comment]
DId it stay like that indefinitely?  I've seen that before, but it usually shows the data after a minute or so.

**Comment by amerzang** [comment]
it stays like that, then the loading circle goes away.

**Comment by amerzang** [comment]
i don't know if it matters, but i use 3 monitors.

**Comment by amerzang** [comment]
I think i found the answer, yesterday, when i started my PC, i opened outlook before ootd loaded and my appointments showed up. So, i added outlook to the startup folder, so it opens with the pc, and today, my appointments are there again. It seems that outlook has to be open before ootd. Seems that the instance of outlook opened by ootd, isn't correct.

**Comment by amerzang** [comment]
well, that wasn't it, i changed views and when i went back to calendar, had no more appointments. also added some new appointments, tried a restart and they didn't come back.

**Comment by mscrivo** [comment]
So you're seeing that only the new stuff is not appearing in OotD? or nothing at all?  I haven't seen this problem before.  But the fetching of data from Outlook is really out of my control.  The Outlook View Control that I'm using takes care of all that for me.

**Comment by amerzang** [comment]
it seems to be working today, as long as outlook is open before ootd. the other day, i changed to inbox view, then back to calendar, and nothing came back to calendar, but inbox shows everytime.
