### ISSUE TITLE
ootd disappears when pressing the show desktop button or selecting "show desktop" from task bar contect menu

### ISSUE THREAD

**Issue by MorAisenberg** [mscrivo/ootd#24]
ootd disappears when pressing the show desktop button or selecting "show desktop" from task bar contect menu.

**Comment by mscrivo** [comment]
That's something that cannot be fixed.  After Windows XP, Microsoft diallowed anything from overriding the show desktop behaviour.  There are some workarounds though, if you want to hide all windows except OotD, you can hover over the bottom right corner of your screen, just beside the time. You can also press the Win+M keys to minimize all windows and then Win+Shift+M to restore them afterwords.

**Comment by MorAisenberg** [comment]
Is it not possible to re-show the application in it lowest z order once in
x seconds?
בתאריך 3 בנוב׳ 2015 16:57,‏ "mscrivo" <notifications@github.com> כתב:

**Comment by mscrivo** [comment]
That's actually what it does already to some extent, and there's probably more things that can be done to hack around it, but everything I've tried in the past either didn't work or resulted in some other unwanted behavior.

**Comment by MorAisenberg** [comment]
OK, very nice work btw.
I think you need to continue working on it since it is possible... look at
fences for example.
If I come across any relevant I'll notify you.
בתאריך 3 בנוב׳ 2015 18:20,‏ "mscrivo" <notifications@github.com> כתב:

**Comment by MorAisenberg** [comment]
Relevant code
בתאריך 3 בנוב׳ 2015 18:23,‏ "Mor Aisenberg" <mor.aisenberg@gmail.com> כתב:
