### ISSUE TITLE
Never ending loading bar

### ISSUE THREAD

**Issue by newtonianb** [mscrivo/ootd#25]
I'm trying to get my iCloud calendar to show and it seems to be working but I get a never ending loading bar on my calendar. The content is displayed in the calendar though.

![2015-11-04_10-55-25](https://cloud.githubusercontent.com/assets/2313644/10943505/a2206144-82e2-11e5-8158-ec247ce1803c.jpg)

**Comment by newtonianb** [comment]
Actually it seems it dissapears after a long long while, normal it takes so long?

**Comment by mscrivo** [comment]
I've seen this issue myself, and have not been able to find out what causes it.

**Comment by newtonianb** [comment]
As long as it works at the end I guess it's not a big deal, it does seem to eventually load.
