### ISSUE TITLE
Multiple calendar in the same box

### ISSUE THREAD

**Issue by newtonianb** [mscrivo/ootd#26]
I usually organize events in different calendars, in outlook it's convenient I can see a merged view all on one calendar, can I do this with ootd?

**Comment by amerzang** [comment]
i could not find a way to do that either, i ended up merging my calendars

**Comment by mscrivo** [comment]
Sorry guys, that's not something that's possible with the Outlook View Control.  It only allows you to use views that exist within Outlook itself.

**Comment by udobehm** [comment]
Hi, Cal4Desktop offers the function to show several calendars overlaid on the desktop (see https://www.somebytes.de/produkte/cal4desktop/). Why is it not possible to program that with your program?? I absolutely need this function :((
