### ISSUE TITLE
Drag and drop of files

### ISSUE THREAD

**Issue by ahmetlee** [mscrivo/ootd#27]
I don't drag and drop of tasks on ootd calendar in month view. I am using Microsoft outlook 2010. Help please.

**Comment by mscrivo** [comment]
I had never tried dragging and dropping on to the tasks view, but just did right now with Office 2016, seemed to work fine.   Has this ever worked for you?

**Comment by ahmetlee** [comment]
Yes worked for me in older version ootd with microsoft office 2003 but now dont work.

**Comment by mscrivo** [comment]
I am unable to drag and drop files in the month view, but I can drop them in the tasks view.  I believe this might just be a limitation of specific versions of Outlook.  I also can't drag and drop into the month view in Outlook 2016 itself.  It says: "Cannot copy the items"
