### ISSUE TITLE
Shared Mailbox Support - Office 365

### ISSUE THREAD

**Issue by ottermutt** [mscrivo/OotD#28]
Office 365 Small Business Premium
Windows 7
Outlook 2016 x64

Hi,
Really nice looking product. It would be nice if there was support for shared mailboxes so that the user could specify which calendar/inbox/task folder gets displayed on each instance.

Apologies, first time Git user so not aware of protocol or formalities.

Thanks!

**Comment by mscrivo** [comment]
Two problems: 

1. I don't have an Office 365 multi-user account to test with
2. I don't believe the Outlook View Control (which OotD uses), supports that.

Perhaps someone familiar with programming and with access to the above scenario would be willing to do some investigation?

**Comment by ottermutt** [comment]
​Thanks for the response-

1. To my knowledge shared mailboxes aren't specified as users within
outlook. Just folders. Regardless, I'm sure you'd need an Office 365
account for development purposes. If you decide to actively work on it
please let me know and I will try to get my employer to sponsor this
project and pay for the license fees.

2. That's a shame. I will take a look myself when I have some time on my
hands. Hopefully some sort of workaround exists.

​

**Comment by mscrivo** [comment]
Thanks @ottermutt that's a generous offer.  I would prefer if you would try taking a stab at it first since you have the testing environment already setup.  I can certainly help if you get stuck at any point.
