### ISSUE TITLE
Can't download the latest version since 3.2.6

### ISSUE THREAD

**Issue by BackupTheWolrd** [mscrivo/ootd#29]
It seems the download server can't be accessed.When I open  the 3.3.0.exe link or 3.2.6 to download ,it says failed but the previous editon is ok .I like this app very much ,so plz help me to get the latest one ,wish you send one to my mail is 4682532@163.com or lmy999@hotmail.com

**Comment by mscrivo** [comment]
Just go to the releases page and grab it.
