### ISSUE TITLE
Include Outlook Calender weather banner

### ISSUE THREAD

**Issue by Badger7** [mscrivo/ootd#34]
Include Outlook Calender weather banner

evidently it is limited to a three day forecast

**Comment by mscrivo** [comment]
I'm not sure if this is worth doing (or even possible).  There are so many good weather widgets out there, much better than I could include here.

**Comment by Badger7** [comment]
Its focus.  Having just what you want, without clutter, easily in view.

 

It was just a thought.  I’ll forget my umbrella in any case.  I have Yahoo weather and weather underground as favorites in Chrome.  Just need to remember to look.  

 

Thanks for reply
