### ISSUE TITLE
Window placed off-screen

### ISSUE THREAD

**Issue by kristianrl** [mscrivo/ootd#35]
The top of the window appears off-screen, and I can't move it back using the regular techniques described in eg https://askleo.com/how_do_i_move_an_offscreen_window_in_windows_7/

Is there a way to 'move' the window when I can't click the title bar?

**Comment by mscrivo** [comment]
Are you comfortable with editing your registry?  If you open up regedit and search for "outlook on the desktop" you'll find the instances and values for their window locations. You can edit that directly or delete the whole outlook on the desktop key if you want to start from scratch.

**Comment by kristianrl** [comment]
I'm sorry, but I was unable to find the location. It was neither in `HKEY_USERS\S-1-5-21-900455573-745634022-4263236235-49835\Software\SMR Computer Services\Outlook on the Desktop`,  `HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{6D9785D9-FF53-4C06-9C2A-E4173D41A2FD}_is1` or `HKEY_CURRENT_USER\Software\SMR Computer Services\Outlook on the Desktop`, which are the three results I get.

Can you point me in the right direction?

**Comment by mscrivo** [comment]
Sorry about that.  When I wrote my original comment, I was not at my computer.  In regedit, navigate to HKEY_CURRENT_USER\SOFTWARE\SMR Computer Services\Outlook on The Desktop.  In there, you will see a folder for each of your instances.  If you click on one, you'll see properties for Top, Left, Height and Width.  You probably want to adjust the value for Top.

**Comment by kristianrl** [comment]
Thanks! When changing the Top, Left, Height and Width, it didn't affect the window location.
But deleting the entire instance folder did the trick and reset the instance's window location.
