### ISSUE TITLE
Outlook on the Desktop It can be used in the enterprise? 

### ISSUE THREAD

**Issue by Evgen2016** [mscrivo/ootd#36]
Outlook on the Desktop It can be used in the enterprise? 
The software is free? What type of license? ULA?

**Comment by mscrivo** [comment]
Use it wherever you want, it's completely free. I take no responsibility for any issues it may cause though and can provide no extra support other than through bug reports here on github. This is a hobby project for me and I'm the lone developer for it.

**Comment by Evgen2016** [comment]
Спасибо!
