### ISSUE TITLE
Error message when computer starts up and tries to launch the application

### ISSUE THREAD

**Issue by DarrenKF** [mscrivo/ootd#37]
![outlook on the desktop error](https://cloud.githubusercontent.com/assets/16704744/12327123/461c4cce-ba9a-11e5-92a9-1f288618e45a.JPG)

**Comment by mscrivo** [comment]
Does that happen every time?  I think OotD may be trying to startup before Outlook is ready to be loaded.

**Comment by mscrivo** [comment]
See here for a possible fix:  [https://support.microsoft.com/en-us/kb/870655]
