### ISSUE TITLE
Problem installing OotD

### ISSUE THREAD

**Issue by jmgraves** [mscrivo/ootd#38]
It appears that this is a solution I have been looking for for years, and I see no others like it.  My problem is that I can't get OotD to install.  I am running Win 10 64bit.  When I try to install, I get an error message stating that I need to install the correct version.  I have tried to install the 64 bit version without luck.  Any help would be appreciated.

**Comment by mscrivo** [comment]
Did you try the 32-bit version?  What version of Office do you have?

**Comment by jmgraves** [comment]
I’m using Office 2016 on a 64 bit machine.  Does this software interface with Outlook or is it simply a calendar that stays on the desktop?  I need the interface.

**Comment by mscrivo** [comment]
It does interface with Outlook, fully interactive.  Sounds like you should try installing the 32-bit version of OotD
