### ISSUE TITLE
Feature Request: Color Customization

### ISSUE THREAD

**Issue by JBrewer09** [mscrivo/ootd#39]
This is purely aesthetical I know, but I would REALLY love a way to do this... 
Would it be possible to change color/theme in addition to transparency?
I'm currently using this with Rainmeter and Fences and everything else on the desktop is dark.
The functionality of Outlook On The Desktop is amazing but it really contrasts with darker backgrounds and surroundings and is quite rough on the eyes. Maybe I'm missing something and this is already a feature, but if not would this be something that you would consider adding?
Thanks a bunch!
Love the application!

**Comment by mscrivo** [comment]
I fully admit I'm not the best at making things pretty :)  I figured the transparency coupled with the colors of your background would be enough, but it sounds like you'd want a color overlay that you specify independently?

**Comment by JBrewer09** [comment]
Exactly! Instead of the light blues and whites, would it be possible to get some more color variety? ;)

**Comment by mscrivo** [comment]
Oh you're talking about the actual colors on the calendar.  Unfortunately, I don't have much control over that and Outlook doesn't really let you customize it all that much either.  However, you can change the default blue to something else.  Follow these instructions:

1. Click the File tab.
2. Click Options.
3. Click Calendar.
4. Under Display Options, click Default calendar color, click the color that you want, and then select the Use this color on all calendars check box.
