### ISSUE TITLE
Outlook on the desktop - is outside the screen 

### ISSUE THREAD

**Issue by zoopo1** [mscrivo/ootd#40]
Hi there

The outlookonthedesktop window for some reason has gone outside the parameters of the screen. I can only view part of the outlookonthedesktop window. See image attached.

Tried uninstalling and reinstalling with no luck. 

Any help appreciated.

![outlook on desktop](https://cloud.githubusercontent.com/assets/17270514/13074562/29e0f39e-d49d-11e5-8d15-51170bd7da07.jpg)

**Comment by mscrivo** [comment]
Open regedit and navigate to `HKEY_CURRENT_USER\SOFTWARE\SMR Computer Services'  Delete the whole 'Outlook on the Desktop' registry key to reset your installation.  I've been meaning to move this configuration out of the registry for a while.
