### ISSUE TITLE
It appears you are attempting to run an incorrect version

### ISSUE THREAD

**Issue by StevieIrv** [mscrivo/ootd#42]
Please help with the following error message when starting ootd:

![image](https://cloud.githubusercontent.com/assets/17743702/13635508/0d058394-e5f4-11e5-8513-83efffcc2fb2.png)

I installed the 32bit version of ootd and am running Windows 7 32bit with 32bit Office 2007

**Comment by mscrivo** [comment]
That message can also pop up when your outlook installation is corrupted.  Please reinstall office and try again.
