### ISSUE TITLE
Email is not refreshing

### ISSUE THREAD

**Issue by stephanstricker** [mscrivo/ootd#46]
I use this tool and really like it but when I start the application it opens outlook with it. When I use this instance of outlook my email inbox is no longer refreshed. I have to manually synchronize my emails to make them show up.

**Comment by mscrivo** [comment]
Does that also happen if you start Outlook before starting OotD?  I can't think of why this would happen, other than it being a bug in Microsoft's Outlook View control.  

Also, what view(s) do you have configured in OotD?  Is it just your calendar? or do you have the inbox showing as well?

**Comment by stephanstricker** [comment]
When I open outlook first and then start OotD it opens another instance of Outlook. I am not sure if that is how it is supposed to be. When I close the second instance OotD no longer syncs. The instance that I open first syncs emails fine.

**Comment by mscrivo** [comment]
hmm it shouldn't be opening another instance of Outlook.  Is it possible you have more than one version of Office/Outlook installed?
