### ISSUE TITLE
ability to set update frequency

### ISSUE THREAD

**Issue by wallymann** [mscrivo/ootd#47]
the calendar view often sits idle for extended periods and the "current time" bar never moves. a quick glance will suggest that i have plenty of time before an appointment...but then i look at the clock and realize i'm late and that OOTD just hasnt refreshed!  

it would be great to allow the calendar-view to auto-refresh at some user-defined interval.

**Comment by mscrivo** [comment]
It should definitely auto refresh, thanks for bringing this to my attention.

**Comment by mscrivo** [comment]
I just tested this here and after an hour or so, the line indicating the current time is correctly moving on its own in the OotD calendar view.  Perhaps this is a bug with the particular version of Outlook you are using.

**Comment by wallymann** [comment]
mine doesnt necessarily auto-update, it will sit stationary until i actually click on the widget then the current-time line updates.  should this truly be a continuously updating/moving line?

**Comment by mscrivo** [comment]
Yes. The outlook view control (provided by Microsoft) takes care of all
that stuff. I have no control over how the data is updated within that
control.
