### ISSUE TITLE
Not able to regain its size automatically

### ISSUE THREAD

**Issue by ratnakar1994** [mscrivo/ootd#48]
Hey Dev, First of all... Thanks for developing such a nice software...Here is a bug and a feature request which I found:
BUG:
1. Unable to regain its size after shutdown/restart when I choose to show my one of the 'Internet Calenders'. Screenshots attached

Before Shutdown:
![picture1](https://cloud.githubusercontent.com/assets/18597941/14714114/5e085850-0801-11e6-97af-80ee70d0b9e8.jpg)

After Restart:
![picture2](https://cloud.githubusercontent.com/assets/18597941/14714135/6ffa804c-0801-11e6-9e1c-fdff010c010c.jpg)
1. Feature Request:
   I request you to add a feature that can show my multiple calenders in single instance.

Thanks

**Comment by mscrivo** [comment]
Can you give the latest version a try and reopen if it's still an issue?
