### ISSUE TITLE
error with Outlook 2016 with Windows 10

### ISSUE THREAD

**Issue by vto11** [mscrivo/ootd#49]
Hi,

I installed Office Professional Plus 2016 32Bit version on Windows 10 Ent (CB).  When I launched OotD **after** I already opened Outlook, I got the following error below.  If the Outlook is closed when I launched OotD, it will open Outlook with the MS Office registration window or template which showed the MS Office is not yet registered.  However, the MS Office is indeed already registered.  If I continue to re-register MS Office, it won't fix the problem and the issue comes up again.  Please advise.

--- Error Pop Up Window ---
Unhandled exception has occurred in your application.  If you click Continue,
the application will ignore this error and attempt to continure.  If you click Quit,
the application will close immediately.

The RPC server is unavailable. (Exception from HRESULT: 0x800706BA).

--- Details ---
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Runtime.InteropServices.COMException (0x800706BA): The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)
   at OLXLib.IViewCtl.set_ViewXML(String pVal)
   at AxOLXLib.AxViewCtl.set_ViewXML(String value)
   at OutlookDesktop.Forms.MainForm.SetViewXml(String value)
   at OutlookDesktop.Forms.MainForm.MonthButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1078.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
OutlookDesktop
    Assembly Version: 3.4.0.0
    Win32 Version: 3.4.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Outlook%20on%20the%20Desktop/OutlookDesktop.exe
----------------------------------------
NLog
    Assembly Version: 4.0.0.0
    Win32 Version: 4.2.3.1371
    CodeBase: file:///C:/Program%20Files%20(x86)/Outlook%20on%20the%20Desktop/NLog.DLL
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1075.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.ServiceModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1078.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.Office.Interop.Outlook
    Assembly Version: 15.0.0.0
    Win32 Version: 15.0.4569.1507
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.Office.Interop.Outlook/15.0.0.0__71e9bce111e9429c/Microsoft.Office.Interop.Outlook.dll
----------------------------------------
office
    Assembly Version: 15.0.0.0
    Win32 Version: 15.0.4613.1000
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/office/15.0.0.0__71e9bce111e9429c/office.dll
----------------------------------------
NetSparkle
    Assembly Version: 1.0.22.0
    Win32 Version: 1.0.22
    CodeBase: file:///C:/Program%20Files%20(x86)/Outlook%20on%20the%20Desktop/NetSparkle.DLL
----------------------------------------
AxInterop.Microsoft.Office.Interop.OutlookViewCtl
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Outlook%20on%20the%20Desktop/AxInterop.Microsoft.Office.Interop.OutlookViewCtl.DLL
----------------------------------------
OLXLib
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Outlook%20on%20the%20Desktop/OLXLib.DLL
----------------------------------------
MACTrackBarLib
    Assembly Version: 1.0.5932.37702
    Win32 Version: 1.0.5932.37702
    CodeBase: file:///C:/Program%20Files%20(x86)/Outlook%20on%20the%20Desktop/MACTrackBarLib.DLL
----------------------------------------
Microsoft.Office.Interop.OutlookViewCtl
    Assembly Version: 15.0.0.0
    Win32 Version: 15.0.4569.1507
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.Office.Interop.OutlookViewCtl/15.0.0.0__71e9bce111e9429c/Microsoft.Office.Interop.OutlookViewCtl.dll
----------------------------------------
CustomMarshalers
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/CustomMarshalers/v4.0_4.0.0.0__b03f5f7f11d50a3a/CustomMarshalers.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

---

**Comment by mscrivo** [comment]
If when launching outlook, the registration window pops up, then that's why you're getting the error above.  It's waiting for outlook to be available, but that registration window is blocking it from being available.

If when you launch outlook, it launches fine, ie. no windows pop up asking you for information, then it's possible you have another version of outlook on your system that OotD is trying to launch.   But essentially, this is not a problem with OotD, there is some issue with your office installation that you have to get sorted out.
