### ISSUE TITLE
Latest update causes hangs with Outlook/Exchange

### ISSUE THREAD

**Issue by dvrx** [mscrivo/ootd#5]
Ever since upgrading to the most recent version (3.2.3.0), Outlook frequently hangs and becomes unresponsive.  When it's not unresponsive, I often find that my Outlook is disconnected from our Exchange server, requiring either an explicit reentry of my password ("Type Exchange password and connect" ribbon option) or a manual Send/Receive.

Exiting OOTD resolves the issue and Outlook continues to function normally without any Exchange connectivity issues.

**Comment by mscrivo** [comment]
Can you try going back to 3.2.2 (or whatever version you were using before) to confirm it's an actual issue with the latest?  I can't think of anything I changed that would cause that behavior, need to narrow it down a bit more.

**Comment by mmamula** [comment]
I can the same thing. Also, if I terminate OOTD then Outlook becomes responsive immediately.
Today I reverted to 3.2.1 (the version I had before update), no issues.

**Comment by mscrivo** [comment]
Interesting, thanks for the report .. I'll look into it.

**Comment by mscrivo** [comment]
Can either of you try 3.2.2 and see if the problem exists there?

**Comment by dvrx** [comment]
I reverted to 3.2.1.0 without issues.  I'll try 3.2.2 next.

**Comment by dvrx** [comment]
Scratch that!  3.2.2.0 binaries aren't available on the release history page.  Should I grab it from somewhere else?

**Comment by mscrivo** [comment]
there are here: https://github.com/mscrivo/ootd/releases

**Comment by dvrx** [comment]
yep, found it.  You posted your comment just as I deleted mine  :)

**Comment by dvrx** [comment]
I installed 3.2.2 and experienced similar issues.  I think that during a send/receive, things get hosed up - either with the exchange server or with synchronizing with SharePoint tasks (?).  As soon as I killed OOTD, Outlook completed the send/receive immediately and continued to operate without issues.

For now, I'll go back to 3.2.1.

**Comment by mscrivo** [comment]
Thanks, I'll post an update here when I figure it out.

**Comment by mscrivo** [comment]
Can you guys try out this build and see if it makes any difference please?  https://github.com/mscrivo/ootd/releases/tag/3.2.3.1

I reverted the one change that could have possibly caused the issue.

**Comment by mscrivo** [comment]
Either of you have a chance to give it a try?

**Comment by dvrx** [comment]
I've been running the new version for a couple hours and so far I haven't experienced an issue.

**Comment by mscrivo** [comment]
Thanks, I'm going to consider this fixed then.
