### ISSUE TITLE
Choose a certain calender from outlook 2013 in the Ootd / Is that possible

### ISSUE THREAD

**Issue by DaColeman** [mscrivo/ootd#50]
Hi guys,
I have 3 calenders in Outlook 2013. "Mycalender", calender from my Iphone, and my ICloud calender. Is that possible that I can customize the Iphone calender a the Default calender in my view from OotD, and when yes, how does it work?

Thanx in front for an answer and a great Sunday to all you guys,

Da Coleman

**Comment by mscrivo** [comment]
You should be able to select any calendar you want by right clicking on the tray icon and clicking "Choose folder"
