### ISSUE TITLE
New feature: Including upcoming meetings on reading pane on right

### ISSUE THREAD

**Issue by clorrey** [mscrivo/OotD#52]
We would purchase this app for many people in our company if there was a view that included the list of upcoming meetings that is viewable on the far right. Including a snip. 

This shows what meetings you have upcoming this week, so it is easy to glance at and plan. Love the software otherwise. 
![outlookonthedesktop](https://cloud.githubusercontent.com/assets/19476997/15404970/f4769130-1dcd-11e6-8a50-a48b883ebfee.GIF)

**Comment by mscrivo** [comment]
Good suggestion.  At first glance, it doesn't seem this is possible with the Outlook view control that this software uses, but I'll have a deeper look.
