### ISSUE TITLE
Could not read the calandar.

### ISSUE THREAD

**Issue by VPJP** [mscrivo/ootd#54]
For some reason I get this outlook email message every time ootd opens.  I've tried the following:

1) opening ootd as administrator
2) scanpst on outlook .pst file

It happens whether outlook itself is open or not.  Once I click OK, it loads the calendar fine on ootd.  Big problem is because this is an outlook error, outlook itself is "on hold" until the OK button is pressed.  Thus outlook does not process batch email checks or any other function.  This is a mission critical computer at my business so a whole lot of automation is rendered inoperative because of this error. However, my use of ootd is indespensible, so I need to find a work around.

Any idea how I can resolve this problem.  I would gladly donate to expidite and solve this problem.

PS.  I absolutely love this software, been using it for 2 years and find it absolutely indispensable!  It has made me ultra efficient, I could not operate with out it!

**Comment by VPJP** [comment]
Sorry the message is "Could not read the calendar."  OK Button.  Window tittle "Microsoft Outlook".

**Comment by MrCaspan** [comment]
I am having the same issue with Office 2013, no matter what I do i have this error. I am using Exchange 2013 and Outlook.com emails in my outlook!

**Comment by mscrivo** [comment]
Does it only happen when starting OotD?  Does it ever happen with Outlook
directly?  There are some tips here for troubleshooting/possible fixes:
https://social.technet.microsoft.com/Forums/office/en-US/5ea68283-9498-44f7-8e26-7edba74560f3/outlook-2010-error-could-not-read-the-calendar-the-connection-to-microsoft-exchange-is?forum=outlook

**Comment by VPJP** [comment]
Hi Michael,

 

Thanks for the response.

 

It only happens when starting ootd.  Does not happen when opening outlook itself.

 

Thanks for the link, that link was one of the first ones I ran across as well.  I’ve done all sorts of “fixes” on the outlook file itself including the ones listed in this link:

 

1)       I Did “reset the view” in outlook

2)      I did run scanpst.

3)      I have all the plugins disabled, even went through the trouble of deleting all of them.

 

I am not using outlook exchange.  I am using Office Outlook 2013 desktop version.

 

Whatever is going on with the file, Outlook does not have an issue, ootd does.

 

John P. Pariso
Vice President /Owner
 <http://www.vpfinish.com/> www.vpfinish.com

**Comment by mscrivo** [comment]
Thanks John, I'll see what I can do.  One other question, once you get that
error, does it work normally?  do the calendar items show up?

**Comment by VPJP** [comment]
I should also note, that it has happened on two seperate computers, as I migrated over to a new computer recently.  So it appears isolated to the outlook file itself.

**Comment by VPJP** [comment]
Yes, once I get the error, usually overnight after an automatic reboot or something, when I arrive in the morning, I hit OK and the ootd does load the calendar without issue.

**Comment by VPJP** [comment]
One more thing I noticed, I don’t often change calendar views. I always leave it on monthly view.  But I just found out if I use the upper taskbar in ootd to switch to any of the other views (such as weekly) the error pops up each time the switch is made.  FYI

 

John P. Pariso
Vice President /Owner
 <http://www.vpfinish.com/> www.vpfinish.com

**Comment by mscrivo** [comment]
I've tried, but I am unable to reproduce this.  This seems to be a systemic problem with Outlook that happens with certain configurations.  There are some things to try to resolve this issue on this page: https://social.technet.microsoft.com/Forums/office/en-US/5ea68283-9498-44f7-8e26-7edba74560f3/outlook-2010-error-could-not-read-the-calendar-the-connection-to-microsoft-exchange-is?forum=outlook

If any of the them work, I'd be interested to hear about it.
