### ISSUE TITLE
Calendar forward & back buttons

### ISSUE THREAD

**Issue by DWGarwood** [mscrivo/OotD#55]
For some reason, when I try using the forward & back buttons on my OotD instances, it jumps between months (March to December to July and so forth). This is happening on the daily, weekly and monthly views. Other than that, I'm loving this app and wouldn't be without it!

**Comment by Ivkosky** [comment]
I have experienced the same issue.

**Comment by mscrivo** [comment]
I'm unable to repro this one, if either of you can figure out what sequence of events triggers it, please let me know.

**Comment by DWGarwood** [comment]
Hi Michael,

This seems to be working for me now, since I re-installed Windows on my PC.
Thanks for following up on this.

Massive fan of OOTD!

David
