### ISSUE TITLE
On a surface 4 pro with outlook 2016?

### ISSUE THREAD

**Issue by hangrymarc** [mscrivo/OotD#57]
Hello,
I couldn't install on a surface pro 4
Error message :  "install 64 bit version on 64 bit computer or 32 bit on 32 bit computer"
Thnks

**Comment by hangrymarc** [comment]
neither 3.3 or 3.4 version is able to install

**Comment by mscrivo** [comment]
Which version of Microsoft Office do you have installed? 32-bit or 64-bit?  You need to pick the corresponding OotD to whatever version of Office you have installed.
