### ISSUE TITLE
Change color scheme?

### ISSUE THREAD

**Issue by greenbrad** [mscrivo/OotD#60]
Hi,

Love OotD, however I don't have pigmentation on the back of my eyes; and I usually work on my computer in the evening which can lead to a lot of eye strain. Could you add a dark theme, or support for themes? I wouldn't mind contributing to the project if there were a decent API in place.

**Comment by mscrivo** [comment]
You can select your color scheme in Outlook's settings.  For example, here's what it looks like when I select the Dark theme:

![image](https://cloud.githubusercontent.com/assets/275524/24077469/8b162886-0c24-11e7-8742-0c68da057b46.png)
