### ISSUE TITLE
32Bit or 64Bit

### ISSUE THREAD

**Issue by asimonds1776** [mscrivo/OotD#63]
Love this program, however it is not working on all of the machines.  I have a few that say that I need either 32 Bit version or 64 Bit Version.  I have tried both and neither work.  All of the machines are running 64 Bit Windows 10 and either 32 Bit 2003 Outlook or 32 Bit 2007 Outlook

**Comment by mscrivo** [comment]
Can you attach the log files here of the machines that fail?  It will be in either `C:\Program Files (x86)\Outlook on the Desktop` or `C:\Program Files\Outlook on the Desktop`

**Comment by mscrivo** [comment]
Requested log files were not provided.
