### ISSUE TITLE
Automatic Formatting

### ISSUE THREAD

**Issue by asimonds1776** [mscrivo/OotD#64]
The automatic formatting resets every time I turn the computer off.  Is there anyway to make the settings stick?

**Comment by mscrivo** [comment]
which automatic formatting are you referring to?

**Comment by mscrivo** [comment]
Can you tell me exactly how you setup these autoformatting rules?  I've never used them before.  Thanks!

**Comment by asimonds1776** [comment]
Right click on any day and select automatic formatting at the bottom.
