### ISSUE TITLE
Not seeing the calendar view control buttons

### ISSUE THREAD

**Issue by RedX2501** [mscrivo/OotD#65]
Using version 3.5.0 with Outlook 2013 the select calendar view buttons are not shown.

Basically these buttons are missing:

![missing buttons image](https://outlookonthedesktop.com/sites/default/files/ControlBar_0.jpg)

**Comment by Nimrod189** [comment]
I have the same Problem.

My OS: Windows 10 and Office 2010.

**Comment by mscrivo** [comment]
this seems to happen when you select a Calendar that is not your default one.

**Comment by RedX2501** [comment]
Just tried 3.5.1 and problem is still present.

**Comment by Nimrod189** [comment]
I have install the update 3.5.1 and also I still have the same problem.

**Comment by mscrivo** [comment]
hmm ok, I'll double check what happened there.  Can you guys confirm that it works if you have the default calendar selected?

**Comment by Nimrod189** [comment]
I have twice instances und the calender is the default.
Here is a picture: [https://picload.org/image/rcaadlcr/image.png](url)

**Comment by RedX2501** [comment]
I only have one calender afaik. Not sure how to select the default calender. I'm new to outlook.

**Comment by doogil** [comment]
i have the same problem. 
 - windows7 Ent.k
 - intalled "D : "
 - outlook 2010.
 - OotD 3.5.1

**Comment by mscrivo** [comment]
Can those with the problem please give me some details of their display config?  How many monitors, what resolution are they, scaling on each?

**Comment by mscrivo** [comment]
also some screenshots of the problem would help

**Comment by Nimrod189** [comment]
- OS: Windows 10
- MS Office 2010
- OoD 3.5.1
- Installed on D:\

**Comment by Khalliys** [comment]
Just downloaded Outlook on the Desktop and have the same problem. The view buttons are not shown. It looks the same as in doogil's first screenshot. The upper bar only shows the slider on the left and nothing else. It's a little annoying because I can't seem to find a way to change to month view and if I accidentally switch to the detail view of a day I have to close the programm to get the week view back.

- Windows 10
- MS Office 2010
- OoD 3.5.1
- Monitor res: 1920 x 1080

**Comment by mscrivo** [comment]
Can those of you who still have this problem update to 3.5.2 and then attach your log file from `C:\Program Files (x86)\Outlook on the Desktop\logs` or `C:\Program Files\Outlook on the Desktop\logs`.  That should help me get to the bottom of this.

**Comment by Nimrod189** [comment]
Hallo mscrivo,

here my Log-File:

> 2017-08-19 09:26:34.1123 DEBUG Checking to see if there is an instance running. 
> 2017-08-19 09:26:34.1414 DEBUG Successfully read reg key: HKLM\Software\Microsoft\Office 
> 2017-08-19 09:26:34.1414 DEBUG Analyzing subkey '11.0' 
> 2017-08-19 09:26:34.1414 DEBUG Office Version: 11 Detected 
> 2017-08-19 09:26:34.1525 DEBUG Office Version: 11 Detected 
> 2017-08-19 09:26:34.1525 DEBUG Office 2003 or higher is installed, now checking for Outlook exe 
> 2017-08-19 09:26:34.1525 DEBUG Office path reported as: C:\Program Files (x86)\Microsoft Office\Office14\ 
> 2017-08-19 09:26:34.1525 DEBUG Checking for Outlook exe in: C:\Program Files (x86)\Microsoft Office\Office14\ 
> 2017-08-19 09:26:34.1525 DEBUG Outlook exe found.  We're all good. 
> 2017-08-19 09:26:34.2958 INFO Starting the instance manager and loading instances. 
> 2017-08-19 09:26:34.3781 DEBUG Loading app settings from registry 
> 2017-08-19 09:26:34.3781 DEBUG Settings Found. 
> 2017-08-19 09:26:34.3871 DEBUG Multiple instances to load 
> 2017-08-19 09:26:34.3871 DEBUG Instantiating instance Default Instance 
> 2017-08-19 09:26:35.3577 DEBUG Showing Instance Default Instance 
> 2017-08-19 09:26:35.3827 DEBUG Instantiating instance Tasks 
> 2017-08-19 09:26:36.1077 DEBUG Showing Instance Tasks 

Sorry, but the Buttons will not show. I have the same problem.

Nimrod189

**Comment by mscrivo** [comment]
@Nimrod189 that's with the latest 3.5.2 release?  I expected to see some log entries that are not listed in your logs.

**Comment by Nimrod189** [comment]
Sorry, the Update was not completly. I have done again.

Here the new Logfile, but I have the same probleme. 

2017-08-20 09:00:55.3853 DEBUG Checking to see if there is an instance running. 
2017-08-20 09:00:55.4023 DEBUG Successfully read reg key: HKLM\Software\Microsoft\Office 
2017-08-20 09:00:55.4023 DEBUG Analyzing subkey '11.0' 
2017-08-20 09:00:55.4023 DEBUG Office Version: 11 Detected 
2017-08-20 09:00:55.4023 DEBUG Office Version: 11 Detected 
2017-08-20 09:00:55.4023 DEBUG Office 2003 or higher is installed, now checking for Outlook exe 
2017-08-20 09:00:55.4023 DEBUG Office path reported as: C:\Program Files (x86)\Microsoft Office\Office14\ 
2017-08-20 09:00:55.4183 DEBUG Checking for Outlook exe in: C:\Program Files (x86)\Microsoft Office\Office14\ 
2017-08-20 09:00:55.4183 DEBUG Outlook exe found.  We're all good. 
2017-08-20 09:00:55.5517 INFO Starting the instance manager and loading instances. 
2017-08-20 09:00:55.6159 DEBUG Loading app settings from registry 
2017-08-20 09:00:55.6199 DEBUG Settings Found. 
2017-08-20 09:00:55.6199 DEBUG Multiple instances to load 
2017-08-20 09:00:55.6369 DEBUG Instantiating instance Default Instance 
2017-08-20 09:00:55.8866 INFO Outlook folder path: \\************\Kalender 
2017-08-20 09:00:56.2947 DEBUG Showing Instance Default Instance 
2017-08-20 09:00:56.3117 DEBUG Instantiating instance Tasks 
2017-08-20 09:00:56.5052 INFO Outlook folder path: \\***************\Aufgaben 
2017-08-20 09:00:56.7820 DEBUG Showing Instance Tasks

**Comment by mscrivo** [comment]
Thank you, I see the problem now.  I didn't realize the calendar name was
localized internally. I have to come up with a different method of
determining when you are on a calendar view.

**Comment by mscrivo** [comment]
Should be fixed in 3.5.3, thank again for your help @Nimrod189!

**Comment by Nimrod189** [comment]
Hi mscrivo,

now, the new Version 3.5.3 works very fine for me.

Thanks for your work.

Nimrod189
