### ISSUE TITLE
Add zoom control

### ISSUE THREAD

**Issue by jrussell11** [mscrivo/OotD#68]
Outlook itself provides a zoom control on the calendar. It would be useful to have this in OotD as well, as presently my day view shows mostly non-working hours: the ranges from 4 am to 9 am, and 5 pm to 11 pm take up about 2/3rds of the view. As a result, the part of my calendar that I actually care about is compressed. Please see the attached image for an example. 

![ootd](https://cloud.githubusercontent.com/assets/16407528/23762045/ba2ea562-04a9-11e7-8ac7-9cd0d7e57e15.jpg)

**Comment by mscrivo** [comment]
This is a good idea, but I'm not sure when I'll have time to implement it.
