### ISSUE TITLE
Interface "stuck" in-between screens

### ISSUE THREAD

**Issue by latscribe** [mscrivo/OotD#71]
Hi,
I accidently moved the position of the app on my desktop screen so that the top part of it is no longer visible from the desktop.
(PLEASE SEE IMAGE)

I'm trying to move it back in the middle of the screen with the mouse, but it now seems impossible. 

How do I move the app now that it's "stuck" in-between screens?

Thanks for your time.

Cheers,
Lawrence
![outlook-on-the-desktop](https://cloud.githubusercontent.com/assets/15968953/25777720/38917504-32ab-11e7-9654-b04b26a9e913.JPG)

**Comment by mscrivo** [comment]
the easiest thing to do would be to delete the instance and re-add it.

**Comment by YitzHandel** [comment]
Mine is also stuck unreachable.  How do I delete an instance.
![image](https://user-images.githubusercontent.com/47528427/52567281-e8e53780-2dd9-11e9-9f7d-e4b28e52877a.png)
