### ISSUE TITLE
Exception on Start - Win 10 / Outlook 2016

### ISSUE THREAD

**Issue by alpencrosser** [mscrivo/OotD#72]
Hi,
i really love you app, but since a few days I get the attached error Message.
![2017-05-11 09_08_27-outlook on the desktop error](https://cloud.githubusercontent.com/assets/28618898/25936791/6c6e620c-3629-11e7-8b34-42fac4256ff0.png)

I'm using Windows 10 Version 1607 (Build 14393.1198) and Office 2016 Version 1703 (Build 7967.2161).
Is there any log that i can deliver?

Thank you for your help!

Regards,
Manuel

**Comment by mscrivo** [comment]
Take a look at the FAQ:  https://outlookonthedesktop.com/faq

there's some suggestions to try to fix your Office installation.
