### ISSUE TITLE
There was an error initializing the application:

### ISSUE THREAD

**Issue by TLFulton** [mscrivo/OotD#73]
![outlookonthedesktoperror](https://user-images.githubusercontent.com/29933567/27889522-f2668558-61ba-11e7-91ea-82d59c114b81.jpg)

![pc specs](https://user-images.githubusercontent.com/29933567/27889786-9ccd63da-61bc-11e7-9c6e-b27d23c42e19.jpg)

**Comment by mscrivo** [comment]
This indicates a problem with your Office installation.  There are various things to try on the [FAQ](https://outlookonthedesktop.com/faq)
