### ISSUE TITLE
OotD Loading & Shown in Task Manager But Nothing Visible

### ISSUE THREAD

**Issue by dumbwithdata** [mscrivo/OotD#76]
I have OotD installed on one computer for quite some time without issue, but just attempted to put it on another computer and am not able to see it on my computer.  It shows up in the notifications and in task manager and I can make changes to it, but nothing shows up on desktop.  It did give me an error a few times stating "Could not read the calendar" but I believe this is because of the view/item I have tried choosing.  I have tried the suggestion of resetting views, repairing pst file, removing and reinstalling OotD, and deleting the registry key that sets location on screen.  None of these have worked.   I am running Windows 7 (64-bit), with Outlook 2013 in Office Professional (32-bit), and connected to Exchange Server.  My other computer that is running it fine has the same configuration with the Exchange Server but is running Outlook 2007 with Windows 10.  Not sure what else I can try here.

Thank you

**Comment by mscrivo** [comment]
That could not read calendar error is something I haven't been able to track down.  Is your office installation fully up to date?

**Comment by dumbwithdata** [comment]
Michael:
Thank you for your prompt response.  I double check and performed updates again to be sure, but I am and appears was already running the most recent version of Outlook 2013.  It appears the error message only comes when I change to particular view or item and the rest of the time the taskbar/notifications make it appear as if all if running fine.  I am wondering if you have had any issue with display utilities specifically for multiple monitors.  I am running numerous monitors with DisplayFusion and wonder if this is causing a bump.  I tried to turn this off and see if their was an improvement, but nothing seemed to work.  Any thoughts?  

Thanks

**Comment by dumbwithdata** [comment]
Michael:

On a side note,  I was using this computer without additional monitors the other day and was surprised to find that OotD appeared and was working properly with no apparent difference between this instance and when it was not working with multiple monitors with the obvious exception being that OotD is visible.  I have tried again to run with multiple monitors and removing DisplayFusion to ensure that OotD is not being suppressed or overrode, but to no avail.  Any thoughts?

Thanks

**Comment by mscrivo** [comment]
See this: https://social.technet.microsoft.com/Forums/ie/en-US/5bf4ad1b-e8fc-40a2-8cdd-5970cfb66b27/outlook-2010-could-not-read-the-calendar?forum=outlook for a possible solution to the "Could not read the calendar" message.
