### ISSUE TITLE
"Reset window position"-feature

### ISSUE THREAD

**Issue by kristianrl** [mscrivo/OotD#77]
Sometimes my OOTD instances end up in weird corners on the screen (I have a dual screen setup, which could be the cause - see issue #35 ):
![2017-11-14 09_41_12-](https://user-images.githubusercontent.com/2519890/32770592-8188b2b6-c920-11e7-8843-8c41577a9b14.png)
There's no way to move it back, but I can reset the position of the window in the registry editor.

Could you implement a "Reset window position"-feature, so it ends up in a window that fits the screen resolution?

**Comment by mscrivo** [comment]
If you could identify the action that causes the jump, that would be amazing!  I haven't been able to reproduce this.  Do you plug/unplug a second monitor?  Does your resolution change as a normal part of your workflow?

**Comment by kristianrl** [comment]
I haven't been able to reproduce the bug.
I don't think it was related to connecting/disconnecting montors, and I don't change resolution.
