### ISSUE TITLE
Error When downloading, reinstalling... OOTD does not seem to like my outlook client... 

### ISSUE THREAD

**Issue by skysco** [mscrivo/OotD#79]
I have installed this app for the second time, and now it refuses to open/display calendar on desktop.... 
My initial purpose for uninstalling, was that when installed; this application simply does not allow me to access my ACTUAL outlook client if need be... I have Office 365, which is giving me Outlook 2016... 
With that, I decided maybe I did something wrong... Reinstalled, only to recieve this error... 
Any help is appreciated... really dig this app and find it super handy to have my class schedule on my desktop! thank you for your hard work and dedication, you truly are making peoples lives easier!
much appreciated!
ps opened the app as admin....(right click .exe and hit run as admin, correct?)
![ootd](https://user-images.githubusercontent.com/32892631/32990257-5f25b8fe-ccf4-11e7-83a9-173bb8f12551.jpg)

**Comment by skysco** [comment]
![untitled](https://user-images.githubusercontent.com/32892631/32990273-9ab3d360-ccf4-11e7-9181-e49f3061480f.png)

Outlook Error, not sure if this is routine/common...

**Comment by lindigreene** [comment]
Having the same basic problem.  Using older Outlook, had to delete Office 365.  After reinstalling OOTD getting error message.
![Error Message](https://user-images.githubusercontent.com/65300837/81837125-05ef4580-950a-11ea-8f09-76b9950d5e66.jpg)
