### ISSUE TITLE
Won't Open with MSOutlook 2003

### ISSUE THREAD

**Issue by anguts** [mscrivo/ootd#8]
HI, won't open, message says only with MS outlook 2003.  I have 2003 installed, and did a repair and a reboot, still says won't work with what I have.  Please check into this. 

New user  M

**Comment by mscrivo** [comment]
Can you please attach your most recent log file?  It can be found in C:\Program Files (x86)\Outlook on the Desktop\logs.

**Comment by mscrivo** [comment]
Can you please try the beta release here: https://github.com/mscrivo/ootd/releases/tag/3.2.4.1 and see if it works for you?  Thanks

**Comment by anguts** [comment]
Hi,
 
Sorry this one didn't work either, same message.  I've lost your email
asking for the log file, please send me again so I can get it for you.
 
Thanks.  YOur product looks like it's exactly what I need.
 

  _____

**Comment by mscrivo** [comment]
open the issue on github and you'll see the instructions.  You'll have to go there anyway to upload the files, not sure it will work through email.

**Comment by mscrivo** [comment]
btw, I just installed Windows 7 and Office 2003 in a virtual machine and the latest release I pointed to above, works just fine.  So this is likely an issue with your Office installation.

**Comment by anguts** [comment]
Hi
 
I've done a repair to the office installation, and then did a reinstall of
the outlook application, then downloaded your program again, still have the
same message - need 2003 or higher.  Well now what shall I do.
 
Sorry I couldn't find the log file you wanted, I don't have a file saying
Outlook under the Program(86).  I have MS office 11,12,13, but I can't see
any logs for OUtlook.
 
Hoping you can help
 
Marion

  _____

**Comment by mscrivo** [comment]
Marion, if you can't provide the log file for me, there isn't much else I can do, I'm sorry.  I've verified that it does work with Windows 7 and Outlook 2003, so that's about all I can do at this point.

**Comment by anguts** [comment]
Sorry, but I've had to delete the program entirely  In fact, I had to
restore my computer to a previous date as your program was causing many
problems with my machine.  I couldn't open Outlook at all after the last
try, so sorry, but I think you really need to QA this program.  It would be
perfect for me.
 
Thanks.

  _____
