### ISSUE TITLE
more sticky on the desktop

### ISSUE THREAD

**Issue by djdehaan** [mscrivo/OotD#82]
Nice product. We are used to such a feature on our phone, crazy that it is not common on windows! But this app does the thing. One issue: when I click bottom-right, the desktop appears. Unfortunately, the OotD is gone then. How do I get the calendar window even more sticky on the desktop?

**Comment by mscrivo** [comment]
I wish there was a way to do this as well. It was possible on Windows XP and below, but in Windows 7 and above, Microsoft took away the apis to do this easily. I'm sure there is a way to do it but it involves a lot of time and research and I have limited time to do that at the moment.
