### ISSUE TITLE
Error message: The .NET Framework 4.7.1 is not supported on this operating system.

### ISSUE THREAD

**Issue by karimarie** [mscrivo/OotD#84]
I am running Windows 10 and .NET Framework 4.6.1. When I try to install .NET 4.7.1., I get a message that says:
****
Blocking Issues:

The .NET Framework 4.7.1 is not supported on this operating system.
****
Is there anything I should be doing differently in order to be able to get OotD running?

**Comment by mscrivo** [comment]
That's odd .. what if you try installing it straight from here: https://www.microsoft.com/en-us/download/details.aspx?id=56115 ?

**Comment by karimarie** [comment]
Got it working--our organization was apparently blocking a needed Windows update that made this work. Thank you anyway!

**Comment by mscrivo** [comment]
Glad to hear that!  I had no idea what could be wrong.
