### ISSUE TITLE
unknown error after installing

### ISSUE THREAD

**Issue by md61267** [mscrivo/OotD#88]
Hi there,
I just installed the latest download of OotD and receive an unknown erroe during the first start.

![grafik](https://user-images.githubusercontent.com/37597506/37681101-06207d06-2c86-11e8-8e24-543d74483406.png)
 
[2018-03-20.log](https://github.com/mscrivo/OotD/files/1831090/2018-03-20.log)

Best regards 
Matthias

**Comment by mscrivo** [comment]
Hi @md61267, can you please attach the log in the specified location?  Thanks

**Comment by md61267** [comment]
Hi there,
the log file is already attached under the image :)

**Comment by mscrivo** [comment]
ah my apologies, totally missed that :)

**Comment by md61267** [comment]
no problem at all. Thanks for your software and your support.

**Comment by mscrivo** [comment]
Hmm it looks like it wasn't able to read from the Registry whether you have Office 32-bit or 64-bit. It also thinks you have both Office 2013 and 2016 installed.  What version of Office do you have installed currently?

Are you comfortable using regedit to check a setting in your registry?

**Comment by md61267** [comment]
Hello Michael,
I had the 32bit version of Office 2013 installed.I just uninstalled every version of office and reinstalled the 32bit Office 2016.
Now it runs like a charm.
Thanks for your support!

Mit besten Grüßen

Matthias Diehl
Datenschutzbeauftragter DSB-TÜV

esd1 UG (haftungsbeschränkt)
Auf der Grub 5
61267 Neu-Anspach
Tel.: +49 6081 92631-0
Fax: +49 6081 92631-99
m.diehl@esd1ug.de<mailto:m.diehl@esd1ug.de>
www.esd1ug.de<http://www.esd1ug.de/>

Handelsregister: Amtsgericht Bad Homburg v.d.Höhe - HRB12698
Geschäftsführer: Matthias Diehl

P.S. Den Text der neuen EU-Datenschutz-Grundverordnung finden Sie übersichtlich aufbereitet unter www.privacy-regulation.eu<http://www.privacy-regulation.eu/>. Das neue Bundesdatenschutzgesetz finden Sie unter www.bdsg2018.de<http://www.bdsg2018.de/>.

Von: Michael Scrivo <notifications@github.com>
Gesendet: Mittwoch, 21. März 2018 02:04
An: mscrivo/OotD <OotD@noreply.github.com>
Cc: Matthias Diehl <m.diehl@esd1.de>; Mention <mention@noreply.github.com>
Betreff: Re: [mscrivo/OotD] unknown error after installing (#88)


Hmm it looks like it wasn't able to read from the Registry whether you have Office 32-bit or 64-bit. It also thinks you have both Office 2013 and 2016 installed. What version of Office do you have installed currently?

Are you comfortable using regedit to check a setting in your registry?

**Comment by mscrivo** [comment]
Glad to hear that!

**Comment by brevan-dangelo** [comment]
I have this exact same error message
I'm running Office 365 32-bit
Any ideas with what's going wrong?

[2019-01-18.log](https://github.com/mscrivo/OotD/files/2773971/2019-01-18.log)
