### ISSUE TITLE
Outlook 2016 x64

### ISSUE THREAD

**Issue by G-Bigo** [mscrivo/OotD#89]
Just reinstalled Windows 10 x64, installed Outlook 2016 x 64, got all Windows updates, set up my Outlook profile.

The installed OotD – and the next thing happening was the application crashing with a huge error list. Attached.

I've read the section about a possibly corrupted MS Office installation, but as told it's basically a fresh installation.

Could it be OotD is incompatible with Outlook x64?

![ootd-errors-on-startup](https://user-images.githubusercontent.com/37943206/38155395-de15e7ca-3477-11e8-8a56-45298016eb2c.png)

**Comment by mscrivo** [comment]
It's compatible with Outlook x64 .. that's odd.   Does it continue happening everytime you restart your computer?
