### ISSUE TITLE
OotD did not start

### ISSUE THREAD

**Issue by KDU300** [mscrivo/OotD#94]
DotD did not start on my Win 10. 
[2018-05-02.log](https://github.com/mscrivo/OotD/files/1966074/2018-05-02.log)

**Comment by mscrivo** [comment]
Thank you, I will take a look.

**Comment by MKBontwikkeling** [comment]
I got the same problem here
[2018-06-20.log](https://github.com/mscrivo/OotD/files/2117886/2018-06-20.log)

**Comment by mscrivo** [comment]
If either of you are still using it/interested in it, can you please try the latest 3.7.5 version and see if it fixes the issue for you?  If it doesn't, please re-open this.
